##
## kaneton
## 
## Makefile
## 
## path          /home/mycure/data/research/projects/kaneton/papers/kaneton
## 
## made by mycure
##         quintard julien   [quinta_j@epita.fr]
## 
## started on    Sun Nov 21 14:13:54 2004   mycure
## last update   Thu Jul 21 20:33:56 2005   mycure
##

#
# file
#

_FILE_			:=		kaneton

#
# dependency
#

include			../makefile.mk
