get.o: get.c \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/kaneton.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/core/core.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/core/types.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/machine/types.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/architecture/types.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/core/error.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/core/id.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/core/init.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/machine/machine.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/glue/glue.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/architecture/architecture.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/architecture/debug.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/architecture/generic/architecture.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/architecture/generic/local.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/architecture/generic/asm.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/architecture/generic/apic.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/architecture/generic/misc.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/architecture/generic/tss.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/architecture/generic/pmode.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/architecture/generic/gdt.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/architecture/generic/idt.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/architecture/generic/paging.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/architecture/generic/ipi.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/architecture/generic/segment.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/architecture/generic/mapping.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/architecture/context.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/architecture/interrupt.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/architecture/syscalls.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/architecture/virtual.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/platform/platform.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/platform/console.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/library/stdarg.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/platform/irq.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/platform/serial.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/platform/timer.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/glue/as.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/glue/cpu.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/glue/event.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/core/event.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/glue/init.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/glue/io.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/glue/message.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/glue/region.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/glue/scheduler.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/glue/segment.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/glue/task.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/glue/thread.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/core/thread.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/core/wait.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/glue/timer.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/core/set.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/core/set-array.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/core/set-bpt.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/core/bpt.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/core/set-ll.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/core/kernel.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/core/segment.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/core/region.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/core/as.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/core/map.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/core/timer.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/core/io.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/core/task.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/core/cpu.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/core/scheduler.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/core/message.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/core/capability.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/core/interface.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/library/library.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/library/types.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/modules/modules.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/modules/console/include/console.h \
 /data/mycure/repositories/kaneton.STABLE/kaneton/include/modules/test/include/test.h \
 get.h ../../../../engine/engine.h
