perror.o: perror.c
quad.o: quad.c /home/mycure/kaneton/libs/klibc/include/klibc.h \
  /home/mycure/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/types.h \
  /home/mycure/kaneton/libs/klibc/include/libdata/malloc.h \
  /home/mycure/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/mycure/kaneton/core/include/arch/machdep/machdep.h \
  /home/mycure/kaneton/core/include/arch/ia32/ia32/ia32.h \
  /home/mycure/kaneton/core/include/arch/ia32/ia32/asm.h \
  /home/mycure/kaneton/core/include/arch/ia32/ia32/multiboot.h \
  /home/mycure/kaneton/core/include/arch/ia32/ia32/paging.h \
  /home/mycure/kaneton/core/include/arch/ia32/ia32/types.h \
  /home/mycure/kaneton/core/include/arch/ia32/ia32/pmode.h \
  /home/mycure/kaneton/core/include/arch/ia32/ia32/stdarg.h \
  /home/mycure/kaneton/core/include/arch/ia32/kaneton/kaneton.h \
  /home/mycure/kaneton/core/include/arch/ia32/kaneton/bootloader.h \
  /home/mycure/kaneton/core/include/arch/ia32/services/cons.h \
  /home/mycure/kaneton/core/include/arch/ia32/kaneton/debug.h \
  /home/mycure/kaneton/core/include/arch/ia32/kaneton/init.h \
  /home/mycure/kaneton/core/include/arch/ia32/services/services.h \
  /home/mycure/kaneton/core/include/arch/ia32/sys/sys.h \
  /home/mycure/kaneton/core/include/arch/ia32/sys/elf.h \
  /home/mycure/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/mycure/kaneton/libs/klibc/include/libstring/printf.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/errno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/limits.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/services.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/quad.h
