#
# ---------- header -----------------------------------------------------------
#
# project       kaneton
#
# license       kaneton
#
# file          /home/mycure/kaneton/export/Makefile
#
# created       julien quintard   [sun jun 10 14:53:00 2007]
# updated       julien quintard   [sun jun 10 14:54:22 2007]
#

#
# ---------- dependencies -----------------------------------------------------
#

include			../environment/env.mk

#
# ---------- directives -------------------------------------------------------
#

.PHONY:		main clear prototypes headers dependencies

#
# ---------- rules ------------------------------------------------------------
#

main:

clear:
	$(call env_remove,$(_EXPORT_).tar.bz2,)

	$(call env_purge)

prototypes:

headers:

dependencies:
