##
## licence       kaneton licence
##
## project       kaneton
##
## file          /home/buckman/kaneton/export/Makefile
##
## created       julien quintard   [fri feb 11 02:59:20 2005]
## updated       matthieu bucchianeri   [tue jan 24 11:44:36 2006]
##

#
# ---------- dependencies -----------------------------------------------------
#

include			../environment/env.mk

#
# ---------- directives -------------------------------------------------------
#

.PHONY:		all clear proto dep

#
# ---------- rules ------------------------------------------------------------
#

all:

clear:
	$(call env_remove,$(_EXPORT_).tar.gz,)

	$(call env_purge)

proto:

dep:
