#
# ---------- header -----------------------------------------------------------
#
# project       kaneton
#
# license       kaneton
#
# file          /home/mycure/kaneton/test/Makefile
#
# created       julien quintard   [fri jun 29 11:19:40 2007]
# updated       julien quintard   [fri jun 29 11:21:03 2007]
#

#
# ---------- dependencies -----------------------------------------------------
#

include			../environment/env.mk

#
# ---------- directives -------------------------------------------------------
#

.PHONY:		main build run clear prototypes headers

#
# ---------- variables --------------------------------------------------------
#

# Temporary, don't know where to put this
# machine dependant .env.conf
_COMPILE_PY_	:=	compile.py
_TEST_LO_	:=	test.lo

#
# ---------- rules ------------------------------------------------------------
#

main:

clear:
	$(call purge,)

prototypes:

headers:
