#
# ---------- header -----------------------------------------------------------
#
# project       kaneton
#
# license       kaneton
#
# file          /home/mycure/kaneton.STABLE/test/configuration/Makefile
#
# created       julien quintard   [wed may 16 18:08:19 2007]
# updated       julien quintard   [wed nov  3 16:02:51 2010]
#

#
# ---------- dependencies -----------------------------------------------------
#

include			../../environment/env.mk

#
# ---------- directives -------------------------------------------------------
#

.PHONY:		main clear

#
# ---------- rules ------------------------------------------------------------
#

main:

clear:
	$(call env_purge)
