/*
 * project       kaneton
 *
 * generated by gen_interface.rb
 *
 */

/*
 * ---------- information -----------------------------------------------------
 *
 * this file implements user side of system calls.
 *
 */

/*
 * ---------- includes --------------------------------------------------------
 */

#include <stdint.h>
#include <core/core.h>
#include <libkaneton.h>

/*
 * ---------- functions -------------------------------------------------------
 */

t_error		as_give(i_task		arg1,
			t_id		arg2)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_AS_GIVE;
  message.u.request.u.as_give.arg1 = arg1;
  message.u.request.u.as_give.arg2 = arg2;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		as_vaddr(t_id		arg1,
			t_paddr		arg2,
			t_vaddr*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_AS_VADDR;
  message.u.request.u.as_vaddr.arg1 = arg1;
  message.u.request.u.as_vaddr.arg2 = arg2;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.as_vaddr.result1;

  return (ERROR_NONE);
}

t_error		as_paddr(t_id		arg1,
			t_vaddr		arg2,
			t_paddr*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_AS_PADDR;
  message.u.request.u.as_paddr.arg1 = arg1;
  message.u.request.u.as_paddr.arg2 = arg2;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.as_paddr.result1;

  return (ERROR_NONE);
}

t_error		as_copy(t_id		arg1,
			t_vaddr		arg2,
			i_as		arg3,
			t_vaddr		arg4,
			t_vsize		arg5)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_AS_COPY;
  message.u.request.u.as_copy.arg1 = arg1;
  message.u.request.u.as_copy.arg2 = arg2;
  message.u.request.u.as_copy.arg3 = arg3;
  message.u.request.u.as_copy.arg4 = arg4;
  message.u.request.u.as_copy.arg5 = arg5;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		as_clone(i_task		arg1,
			t_id		arg2,
			i_as*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_AS_CLONE;
  message.u.request.u.as_clone.arg1 = arg1;
  message.u.request.u.as_clone.arg2 = arg2;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.as_clone.result1;

  return (ERROR_NONE);
}

t_error		as_reserve(i_task		arg1,
			i_as*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_AS_RESERVE;
  message.u.request.u.as_reserve.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.as_reserve.result1;

  return (ERROR_NONE);
}

t_error		as_release(t_id		arg1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_AS_RELEASE;
  message.u.request.u.as_release.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		as_attribute_tskid(t_id		arg1,
			i_task*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_AS_ATTRIBUTE_TSKID;
  message.u.request.u.as_attribute_tskid.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.as_attribute_tskid.result1;

  return (ERROR_NONE);
}

t_error		event_reserve(t_id		arg1,
			t_type		arg2,
			u_event_handler		arg3,
			t_vaddr		arg4)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_EVENT_RESERVE;
  message.u.request.u.event_reserve.arg1 = arg1;
  message.u.request.u.event_reserve.arg2 = arg2;
  message.u.request.u.event_reserve.arg3 = arg3;
  message.u.request.u.event_reserve.arg4 = arg4;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		event_release(t_id		arg1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_EVENT_RELEASE;
  message.u.request.u.event_release.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		event_attribute_type(t_id		arg1,
			t_type*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_EVENT_ATTRIBUTE_TYPE;
  message.u.request.u.event_attribute_type.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.event_attribute_type.result1;

  return (ERROR_NONE);
}

t_error		event_attribute_handler(t_id		arg1,
			u_event_handler*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_EVENT_ATTRIBUTE_HANDLER;
  message.u.request.u.event_attribute_handler.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.event_attribute_handler.result1;

  return (ERROR_NONE);
}

t_error		event_attribute_data(t_id		arg1,
			t_vaddr*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_EVENT_ATTRIBUTE_DATA;
  message.u.request.u.event_attribute_data.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.event_attribute_data.result1;

  return (ERROR_NONE);
}

t_error		io_grant(t_id		arg1,
			i_task		arg2,
			t_uint8		arg3)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_IO_GRANT;
  message.u.request.u.io_grant.arg1 = arg1;
  message.u.request.u.io_grant.arg2 = arg2;
  message.u.request.u.io_grant.arg3 = arg3;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		io_deny(t_id		arg1,
			i_task		arg2,
			t_uint8		arg3)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_IO_DENY;
  message.u.request.u.io_deny.arg1 = arg1;
  message.u.request.u.io_deny.arg2 = arg2;
  message.u.request.u.io_deny.arg3 = arg3;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		io_read_8(i_task		arg1,
			t_id		arg2,
			t_uint8*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_IO_READ_8;
  message.u.request.u.io_read_8.arg1 = arg1;
  message.u.request.u.io_read_8.arg2 = arg2;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.io_read_8.result1;

  return (ERROR_NONE);
}

t_error		io_read_16(i_task		arg1,
			t_id		arg2,
			t_uint16*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_IO_READ_16;
  message.u.request.u.io_read_16.arg1 = arg1;
  message.u.request.u.io_read_16.arg2 = arg2;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.io_read_16.result1;

  return (ERROR_NONE);
}

t_error		io_read_32(i_task		arg1,
			t_id		arg2,
			t_uint32*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_IO_READ_32;
  message.u.request.u.io_read_32.arg1 = arg1;
  message.u.request.u.io_read_32.arg2 = arg2;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.io_read_32.result1;

  return (ERROR_NONE);
}

t_error		io_read_64(i_task		arg1,
			t_id		arg2,
			t_uint64*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_IO_READ_64;
  message.u.request.u.io_read_64.arg1 = arg1;
  message.u.request.u.io_read_64.arg2 = arg2;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.io_read_64.result1;

  return (ERROR_NONE);
}

t_error		io_write_8(i_task		arg1,
			t_id		arg2,
			t_uint8		arg3)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_IO_WRITE_8;
  message.u.request.u.io_write_8.arg1 = arg1;
  message.u.request.u.io_write_8.arg2 = arg2;
  message.u.request.u.io_write_8.arg3 = arg3;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		io_write_16(i_task		arg1,
			t_id		arg2,
			t_uint16		arg3)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_IO_WRITE_16;
  message.u.request.u.io_write_16.arg1 = arg1;
  message.u.request.u.io_write_16.arg2 = arg2;
  message.u.request.u.io_write_16.arg3 = arg3;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		io_write_32(i_task		arg1,
			t_id		arg2,
			t_uint32		arg3)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_IO_WRITE_32;
  message.u.request.u.io_write_32.arg1 = arg1;
  message.u.request.u.io_write_32.arg2 = arg2;
  message.u.request.u.io_write_32.arg3 = arg3;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		io_write_64(i_task		arg1,
			t_id		arg2,
			t_uint64		arg3)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_IO_WRITE_64;
  message.u.request.u.io_write_64.arg1 = arg1;
  message.u.request.u.io_write_64.arg2 = arg2;
  message.u.request.u.io_write_64.arg3 = arg3;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		map_reserve(t_id		arg1,
			t_opts		arg2,
			t_vsize		arg3,
			t_perms		arg4,
			t_vaddr*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_MAP_RESERVE;
  message.u.request.u.map_reserve.arg1 = arg1;
  message.u.request.u.map_reserve.arg2 = arg2;
  message.u.request.u.map_reserve.arg3 = arg3;
  message.u.request.u.map_reserve.arg4 = arg4;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.map_reserve.result1;

  return (ERROR_NONE);
}

t_error		map_release(t_id		arg1,
			t_vaddr		arg2)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_MAP_RELEASE;
  message.u.request.u.map_release.arg1 = arg1;
  message.u.request.u.map_release.arg2 = arg2;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		map_resize(t_id		arg1,
			t_vaddr		arg2,
			t_vsize		arg3,
			t_vaddr*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_MAP_RESIZE;
  message.u.request.u.map_resize.arg1 = arg1;
  message.u.request.u.map_resize.arg2 = arg2;
  message.u.request.u.map_resize.arg3 = arg3;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.map_resize.result1;

  return (ERROR_NONE);
}

t_error		region_reserve(t_id		arg1,
			i_segment		arg2,
			t_paddr		arg3,
			t_opts		arg4,
			t_vaddr		arg5,
			t_vsize		arg6,
			i_region*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_REGION_RESERVE;
  message.u.request.u.region_reserve.arg1 = arg1;
  message.u.request.u.region_reserve.arg2 = arg2;
  message.u.request.u.region_reserve.arg3 = arg3;
  message.u.request.u.region_reserve.arg4 = arg4;
  message.u.request.u.region_reserve.arg5 = arg5;
  message.u.request.u.region_reserve.arg6 = arg6;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.region_reserve.result1;

  return (ERROR_NONE);
}

t_error		region_release(i_as		arg1,
			t_id		arg2)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_REGION_RELEASE;
  message.u.request.u.region_release.arg1 = arg1;
  message.u.request.u.region_release.arg2 = arg2;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		scheduler_quantum(t_quantum		arg1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_SCHEDULER_QUANTUM;
  message.u.request.u.scheduler_quantum.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		scheduler_yield(i_cpu		arg1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_SCHEDULER_YIELD;
  message.u.request.u.scheduler_yield.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		scheduler_current(i_thread*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_SCHEDULER_CURRENT;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.scheduler_current.result1;

  return (ERROR_NONE);
}

t_error		scheduler_add(i_thread		arg1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_SCHEDULER_ADD;
  message.u.request.u.scheduler_add.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		scheduler_remove(i_thread		arg1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_SCHEDULER_REMOVE;
  message.u.request.u.scheduler_remove.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		scheduler_update(i_thread		arg1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_SCHEDULER_UPDATE;
  message.u.request.u.scheduler_update.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		segment_clone(i_as		arg1,
			t_id		arg2,
			i_segment*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_SEGMENT_CLONE;
  message.u.request.u.segment_clone.arg1 = arg1;
  message.u.request.u.segment_clone.arg2 = arg2;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.segment_clone.result1;

  return (ERROR_NONE);
}

t_error		segment_give(i_as		arg1,
			t_id		arg2)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_SEGMENT_GIVE;
  message.u.request.u.segment_give.arg1 = arg1;
  message.u.request.u.segment_give.arg2 = arg2;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		segment_copy(t_id		arg1,
			t_paddr		arg2,
			i_segment		arg3,
			t_paddr		arg4,
			t_psize		arg5)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_SEGMENT_COPY;
  message.u.request.u.segment_copy.arg1 = arg1;
  message.u.request.u.segment_copy.arg2 = arg2;
  message.u.request.u.segment_copy.arg3 = arg3;
  message.u.request.u.segment_copy.arg4 = arg4;
  message.u.request.u.segment_copy.arg5 = arg5;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		segment_reserve(i_as		arg1,
			t_psize		arg2,
			t_perms		arg3,
			i_segment*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_SEGMENT_RESERVE;
  message.u.request.u.segment_reserve.arg1 = arg1;
  message.u.request.u.segment_reserve.arg2 = arg2;
  message.u.request.u.segment_reserve.arg3 = arg3;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.segment_reserve.result1;

  return (ERROR_NONE);
}

t_error		segment_release(i_segment		arg1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_SEGMENT_RELEASE;
  message.u.request.u.segment_release.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		segment_catch(i_as		arg1,
			t_id		arg2)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_SEGMENT_CATCH;
  message.u.request.u.segment_catch.arg1 = arg1;
  message.u.request.u.segment_catch.arg2 = arg2;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		segment_perms(t_id		arg1,
			t_perms		arg2)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_SEGMENT_PERMS;
  message.u.request.u.segment_perms.arg1 = arg1;
  message.u.request.u.segment_perms.arg2 = arg2;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		segment_type(t_id		arg1,
			t_type		arg2)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_SEGMENT_TYPE;
  message.u.request.u.segment_type.arg1 = arg1;
  message.u.request.u.segment_type.arg2 = arg2;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		segment_attribute_asid(t_id		arg1,
			i_as*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_SEGMENT_ATTRIBUTE_ASID;
  message.u.request.u.segment_attribute_asid.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.segment_attribute_asid.result1;

  return (ERROR_NONE);
}

t_error		segment_attribute_type(t_id		arg1,
			t_type*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_SEGMENT_ATTRIBUTE_TYPE;
  message.u.request.u.segment_attribute_type.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.segment_attribute_type.result1;

  return (ERROR_NONE);
}

t_error		segment_attribute_address(t_id		arg1,
			t_paddr*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_SEGMENT_ATTRIBUTE_ADDRESS;
  message.u.request.u.segment_attribute_address.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.segment_attribute_address.result1;

  return (ERROR_NONE);
}

t_error		segment_attribute_size(t_id		arg1,
			t_psize*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_SEGMENT_ATTRIBUTE_SIZE;
  message.u.request.u.segment_attribute_size.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.segment_attribute_size.result1;

  return (ERROR_NONE);
}

t_error		segment_attribute_perms(t_id		arg1,
			t_perms*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_SEGMENT_ATTRIBUTE_PERMS;
  message.u.request.u.segment_attribute_perms.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.segment_attribute_perms.result1;

  return (ERROR_NONE);
}

t_error		task_current(i_task*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_TASK_CURRENT;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.task_current.result1;

  return (ERROR_NONE);
}

t_error		task_clone(t_id		arg1,
			i_task*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_TASK_CLONE;
  message.u.request.u.task_clone.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.task_clone.result1;

  return (ERROR_NONE);
}

t_error		task_reserve(t_class		arg1,
			t_behav		arg2,
			t_prior		arg3,
			i_task*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_TASK_RESERVE;
  message.u.request.u.task_reserve.arg1 = arg1;
  message.u.request.u.task_reserve.arg2 = arg2;
  message.u.request.u.task_reserve.arg3 = arg3;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.task_reserve.result1;

  return (ERROR_NONE);
}

t_error		task_release(t_id		arg1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_TASK_RELEASE;
  message.u.request.u.task_release.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		task_priority(t_id		arg1,
			t_prior		arg2)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_TASK_PRIORITY;
  message.u.request.u.task_priority.arg1 = arg1;
  message.u.request.u.task_priority.arg2 = arg2;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		task_state(t_id		arg1,
			t_state		arg2)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_TASK_STATE;
  message.u.request.u.task_state.arg1 = arg1;
  message.u.request.u.task_state.arg2 = arg2;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		task_wait(t_id		arg1,
			t_opts		arg2,
			t_wait*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_TASK_WAIT;
  message.u.request.u.task_wait.arg1 = arg1;
  message.u.request.u.task_wait.arg2 = arg2;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.task_wait.result1;

  return (ERROR_NONE);
}

t_error		task_attribute_parent(t_id		arg1,
			i_task*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_TASK_ATTRIBUTE_PARENT;
  message.u.request.u.task_attribute_parent.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.task_attribute_parent.result1;

  return (ERROR_NONE);
}

t_error		task_attribute_class(t_id		arg1,
			t_class*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_TASK_ATTRIBUTE_CLASS;
  message.u.request.u.task_attribute_class.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.task_attribute_class.result1;

  return (ERROR_NONE);
}

t_error		task_attribute_behav(t_id		arg1,
			t_behav*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_TASK_ATTRIBUTE_BEHAV;
  message.u.request.u.task_attribute_behav.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.task_attribute_behav.result1;

  return (ERROR_NONE);
}

t_error		task_attribute_prior(t_id		arg1,
			t_prior*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_TASK_ATTRIBUTE_PRIOR;
  message.u.request.u.task_attribute_prior.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.task_attribute_prior.result1;

  return (ERROR_NONE);
}

t_error		task_attribute_asid(t_id		arg1,
			i_as*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_TASK_ATTRIBUTE_ASID;
  message.u.request.u.task_attribute_asid.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.task_attribute_asid.result1;

  return (ERROR_NONE);
}

t_error		task_attribute_sched(t_id		arg1,
			t_state*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_TASK_ATTRIBUTE_SCHED;
  message.u.request.u.task_attribute_sched.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.task_attribute_sched.result1;

  return (ERROR_NONE);
}

t_error		task_attribute_wait(t_id		arg1,
			t_wait*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_TASK_ATTRIBUTE_WAIT;
  message.u.request.u.task_attribute_wait.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.task_attribute_wait.result1;

  return (ERROR_NONE);
}

t_error		thread_give(i_task		arg1,
			t_id		arg2)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_THREAD_GIVE;
  message.u.request.u.thread_give.arg1 = arg1;
  message.u.request.u.thread_give.arg2 = arg2;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		thread_clone(i_task		arg1,
			t_id		arg2,
			i_thread*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_THREAD_CLONE;
  message.u.request.u.thread_clone.arg1 = arg1;
  message.u.request.u.thread_clone.arg2 = arg2;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.thread_clone.result1;

  return (ERROR_NONE);
}

t_error		thread_reserve(i_task		arg1,
			t_prior		arg2,
			i_thread*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_THREAD_RESERVE;
  message.u.request.u.thread_reserve.arg1 = arg1;
  message.u.request.u.thread_reserve.arg2 = arg2;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.thread_reserve.result1;

  return (ERROR_NONE);
}

t_error		thread_release(t_id		arg1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_THREAD_RELEASE;
  message.u.request.u.thread_release.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		thread_priority(t_id		arg1,
			t_prior		arg2)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_THREAD_PRIORITY;
  message.u.request.u.thread_priority.arg1 = arg1;
  message.u.request.u.thread_priority.arg2 = arg2;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		thread_state(t_id		arg1,
			t_state		arg2)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_THREAD_STATE;
  message.u.request.u.thread_state.arg1 = arg1;
  message.u.request.u.thread_state.arg2 = arg2;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		thread_stack(t_id		arg1,
			t_stack		arg2)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_THREAD_STACK;
  message.u.request.u.thread_stack.arg1 = arg1;
  message.u.request.u.thread_stack.arg2 = arg2;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		thread_load(t_id		arg1,
			t_thread_context		arg2)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_THREAD_LOAD;
  message.u.request.u.thread_load.arg1 = arg1;
  message.u.request.u.thread_load.arg2 = arg2;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		thread_store(t_id		arg1,
			t_thread_context*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_THREAD_STORE;
  message.u.request.u.thread_store.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.thread_store.result1;

  return (ERROR_NONE);
}

t_error		thread_attribute_taskid(t_id		arg1,
			i_task*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_THREAD_ATTRIBUTE_TASKID;
  message.u.request.u.thread_attribute_taskid.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.thread_attribute_taskid.result1;

  return (ERROR_NONE);
}

t_error		thread_attribute_prior(t_id		arg1,
			t_prior*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_THREAD_ATTRIBUTE_PRIOR;
  message.u.request.u.thread_attribute_prior.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.thread_attribute_prior.result1;

  return (ERROR_NONE);
}

t_error		thread_attribute_sched(t_id		arg1,
			t_state*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_THREAD_ATTRIBUTE_SCHED;
  message.u.request.u.thread_attribute_sched.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.thread_attribute_sched.result1;

  return (ERROR_NONE);
}

t_error		thread_attribute_wait(t_id		arg1,
			t_wait*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_THREAD_ATTRIBUTE_WAIT;
  message.u.request.u.thread_attribute_wait.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.thread_attribute_wait.result1;

  return (ERROR_NONE);
}

t_error		thread_attribute_stack(t_id		arg1,
			t_vaddr*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_THREAD_ATTRIBUTE_STACK;
  message.u.request.u.thread_attribute_stack.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.thread_attribute_stack.result1;

  return (ERROR_NONE);
}

t_error		thread_attribute_stacksz(t_id		arg1,
			t_vsize*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_THREAD_ATTRIBUTE_STACKSZ;
  message.u.request.u.thread_attribute_stacksz.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.thread_attribute_stacksz.result1;

  return (ERROR_NONE);
}

t_error		timer_reserve(t_type		arg1,
			u_timer_handler		arg2,
			t_vaddr		arg3,
			t_uint32		arg4,
			t_uint32		arg5,
			i_timer*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_TIMER_RESERVE;
  message.u.request.u.timer_reserve.arg1 = arg1;
  message.u.request.u.timer_reserve.arg2 = arg2;
  message.u.request.u.timer_reserve.arg3 = arg3;
  message.u.request.u.timer_reserve.arg4 = arg4;
  message.u.request.u.timer_reserve.arg5 = arg5;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.timer_reserve.result1;

  return (ERROR_NONE);
}

t_error		timer_release(t_id		arg1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_TIMER_RELEASE;
  message.u.request.u.timer_release.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		timer_delay(t_id		arg1,
			t_uint32		arg2)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_TIMER_DELAY;
  message.u.request.u.timer_delay.arg1 = arg1;
  message.u.request.u.timer_delay.arg2 = arg2;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		timer_repeat(t_id		arg1,
			t_uint32		arg2)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_TIMER_REPEAT;
  message.u.request.u.timer_repeat.arg1 = arg1;
  message.u.request.u.timer_repeat.arg2 = arg2;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		timer_modify(t_id		arg1,
			t_uint32		arg2,
			t_uint32		arg3)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_TIMER_MODIFY;
  message.u.request.u.timer_modify.arg1 = arg1;
  message.u.request.u.timer_modify.arg2 = arg2;
  message.u.request.u.timer_modify.arg3 = arg3;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		timer_attribute_delay(t_id		arg1,
			t_uint32*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_TIMER_ATTRIBUTE_DELAY;
  message.u.request.u.timer_attribute_delay.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.timer_attribute_delay.result1;

  return (ERROR_NONE);
}

t_error		timer_attribute_repeat(t_id		arg1,
			t_uint32*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_TIMER_ATTRIBUTE_REPEAT;
  message.u.request.u.timer_attribute_repeat.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.timer_attribute_repeat.result1;

  return (ERROR_NONE);
}

t_error		timer_attribute_type(t_id		arg1,
			t_type*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_TIMER_ATTRIBUTE_TYPE;
  message.u.request.u.timer_attribute_type.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.timer_attribute_type.result1;

  return (ERROR_NONE);
}

t_error		timer_attribute_handler(t_id		arg1,
			u_timer_handler*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_TIMER_ATTRIBUTE_HANDLER;
  message.u.request.u.timer_attribute_handler.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.timer_attribute_handler.result1;

  return (ERROR_NONE);
}

t_error		timer_attribute_data(t_id		arg1,
			t_vaddr*		result1)
{
  o_syscall		message;
  i_node		node;
  t_vsize		size;

  node.machine = 0;
  node.task = 0;

  message.id = 0;

  message.u.request.operation = INTERFACE_TIMER_ATTRIBUTE_DATA;
  message.u.request.u.timer_attribute_data.arg1 = arg1;

  message_send(node, MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, sizeof (message));

  if (message_receive(MESSAGE_TYPE_INTERFACE, (t_vaddr)&message, &size, &node) != ERROR_NONE)
    return (ERROR_UNKNOWN);

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.timer_attribute_data.result1;

  return (ERROR_NONE);
}


