##
## licence       kaneton licence
##
## project       kaneton
##
## file          /home/mycure/kaneton/internship/Makefile
##
## created       julien quintard   [sat jan 21 23:55:55 2006]
## updated       julien quintard   [sat jan 21 23:56:17 2006]
##

#
# ---------- dependencies -----------------------------------------------------
#

include			../env/.env.mk

#
# ---------- directives -------------------------------------------------------
#

.PHONY:		all clear proto dep

#
# ---------- rules ------------------------------------------------------------
#

all:

clear:
	$(call purge,)

proto:

dep:
