#!/bin/sh
## copyright quintard julien
## 
## kaneton
## 
## init
## 
## path          /home/mycure/kaneton
## 
## made by mycure
##         quintard julien   [quinta_j@epita.fr]
## 
## started on    Fri Feb 11 02:58:21 2005   mycure
## last update   Fri Jul  1 13:11:48 2005   mycure
##

# INFORMATIONS
#
# this script has to be run in its directory: src/env/
# or with "make init" in the src/ directory



# CONFIGURATION FILE PATH
#
# the configuration file
CONF="../conf/"$USER"/"$USER".conf"



# CONFIGURATION FILE VARIABLES
#
# default globals
TITLE="unknown"
VERSION="unknown"
LIBC="unknown"
ENVIRONMENT="unknown"
ARCHITECTURE="unknwon"
BOOTLOADER="unknown"
MODE="unknown"



# VERSION HEADER FILE
#
# the version header file to generate
VERSION_H="core/include/version.h"



# INSTALL SPECIFIC VARIABLES
#
# generic names for this script
KANETON_MK=".kaneton.mk"



# READ CONFIGURATION FILE
#
# function used to read the configuration file and to load
# important variables
read_kaneton_conf()
{
  # title
  TITLE=`cat $CONF | grep -E "^_TITLE_ = .*$" | cut -b 11-`

  # version
  VERSION=`cat $CONF | grep -E "^_VERSION_ = .*$" | cut -b 13-`

  # mode
  MODE=`cat $CONF | grep -E "^_MODE_ = .*$" | cut -b 10-`

  # libc
  LIBC=`cat $CONF | grep -E "^_LIBC_ = .*$" | cut -b 10-`

  # environment
  ENVIRONMENT=`cat $CONF | grep -E "^_ENVIRONMENT_ = .*$" | cut -b 17-`

  # architecture
  ARCHITECTURE=`cat $CONF | grep -E "^_ARCHITECTURE_ = .*$" | cut -b 18-`

  # bootloader
  BOOTLOADER=`cat $CONF | grep -E "^_BOOTLOADER_ = .*$" | cut -b 16-`
}



# USAGE
#
# this function displays the usage but does not exit
usage()
{
  print " usage: init" "!"
}



# WARNING
#
# this function alerts the user, displaying information and asking to continue
warning()
{
  # display information and ask the user to continue or cancel
  print " your current configuration:" "+"
  print "   title:                    $TITLE" "+"
  print "   version:                  $VERSION" "+"
  print "   mode:                     $MODE" "+"
  print "   libc:                     $LIBC" "+"
  print "   environment:              $ENVIRONMENT" "+"
  print "   architecture:             $ARCHITECTURE" "+"
  print "   bootloader:               $BOOTLOADER" "+"
  print ""
  print " to cancel press CTRL^C, otherwise press enter" "?"

  NEEDLESS=""
  read NEEDLESS
}



# ENVIRONMENTS
#
# this function displays the supported environments
environments()
{
  list=""

  directory=`ls env`

  for i in env/$directory ; do
    if [ -d env/$i ] ; then
      list="$list $i"
    fi
  done

  print " supported environments are:$list" "!"
}



# INIT
#
# this function installs the environment, calling the script depending
# of your operating system
init()
{
  if [ ! -d env/$ENVIRONMENT ] ; then
    print " unknown system: $ENVIRONMENT" "!"
    print ""
    print " please check your ENVIRONMENT variable in $CONF" "!"
    print ""
    environments
    print ""
    usage
    exit
  fi

  if [ ! -e env/$ENVIRONMENT/init ] ; then
    print " unknown system: $ENVIRONMENT" "!"
    print ""
    print " please check your ENVIRONMENT variable in $CONF" "!"
    print ""
    environments
    print ""
    usage
    exit
  fi

  ./env/$ENVIRONMENT/init
}



# VERSION
#
# this function generates the version header file from the configuration file
version()
{
  print " generating the version header file" "+"

  echo -n "" > $VERSION_H

  echo "#ifndef VERSION_H" >> $VERSION_H
  echo "#define VERSION_H		1" >> $VERSION_H

  echo "" >> $VERSION_H

  echo "#define TITLE			\"$TITLE\"" >> $VERSION_H

  echo "#define VERSION			\"$VERSION\"" >> $VERSION_H

  if [ $MODE = "development" ] ; then
    echo "#define MODE			MODE_DEVELOPMENT" >> $VERSION_H
  fi
  if [ $MODE = "release" ] ; then
    echo "#define MODE			MODE_RELEASE" >> $VERSION_H
  fi

  echo "#define LIBC			\"$LIBC\"" >> $VERSION_H

  echo "#define ENVIRONMENT		\"$ENVIRONMENT\"" >> $VERSION_H

  echo "#define ARCHITECTURE		\"$ARCHITECTURE\"" >> $VERSION_H

  echo "#define BOOTLOADER		\"$BOOTLOADER\"" >> $VERSION_H

  echo "" >> $VERSION_H

  echo "#endif" >> $VERSION_H
}



# DEPENDENCIES
#
# this function generates C files dependencies.
dep()
{
  print " generating files dependencies" "+"

  make dep 2> /dev/null > /dev/null
}



# PRINT A MESSAGE
#
# print a message with a header
print()
{
  msg=$1
  header=$2

  case "$header" in
    "+")
      echo -n -e '\E[;34m'"\033[1m[\033[0m"
      echo -n -e '\E[;32m'"\033[1m+\033[0m"
      echo -n -e '\E[;34m'"\033[1m]\033[0m"
      ;;

    "!")
      echo -n -e '\E[;34m'"\033[1m[\033[0m"
      echo -n -e '\E[;31m'"\033[1m!\033[0m"
      echo -n -e '\E[;34m'"\033[1m]\033[0m"
      ;;

    "?")
      echo -n -e '\E[;34m'"\033[1m[\033[0m"
      echo -n -e '\E[;33m'"\033[1m\033[5m?\033[0m\033[0m"
      echo -n -e '\E[;34m'"\033[1m]\033[0m"
      ;;

    *)
      ;;
  esac

  echo -e "\033[1m$msg\033[0m"
  tput sgr0
}



# ENTRY POINT
#
# entry point of this script

# start of installation

print " installing environment" "+"
print ""

# call the read_kaneton_conf function
read_kaneton_conf

# call the warning function
warning

# go into the src/ directory
cd ../

# install environment
init

# generate the version header file
version

# generate the files dependencies
dep

# return into the env/ directory
cd env/

# end of installation
print " environment installed successfully" "+"
