as.o: as.c /home/vertrex/kaneton/libs/libc.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/types.h \
  /home/vertrex/kaneton/core/include/arch/machdep/machdep.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/ia32.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/asm.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/multiboot.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/paging.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/types.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/pmode.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/stdarg.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/kaneton.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/bootloader.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/cons.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/debug.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/init.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/services.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/sys.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/elf.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/printf.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/errno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/limits.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/services.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/quad.h \
  /home/vertrex/kaneton/core/include/kaneton.h \
  /home/vertrex/kaneton/core/include/version.h \
  /home/vertrex/kaneton/core/include/kaneton/kaneton.h \
  /home/vertrex/kaneton/core/include/kaneton/as.h \
  /home/vertrex/kaneton/core/include/kaneton/id.h \
  /home/vertrex/kaneton/core/include/kaneton/debug.h \
  /home/vertrex/kaneton/core/include/kaneton/init.h \
  /home/vertrex/kaneton/core/include/kaneton/segment.h \
  /home/vertrex/kaneton/core/include/kaneton/set.h \
  /home/vertrex/kaneton/core/include/kaneton/set_array.h \
  /home/vertrex/kaneton/core/include/kaneton/set_ll.h \
  /home/vertrex/kaneton/core/include/services/services.h \
  /home/vertrex/kaneton/core/include/sys/sys.h \
  /home/vertrex/kaneton/core/include/sys/elf.h
