
/**
 ** Auto-generated file, dont modify directly
 ** your changes will be lost !
 **
 ** Generated by DSX on 2006-04-12 16:13:48.075577
 ** by unknown@callisto
 **/
#ifndef _IDCT_PROTO_H
#define _IDCT_PROTO_H

#include <dsx.h>

typedef struct _idct_args_t idct_args_t;
struct _idct_args_t {
	dsx_mwmr_t input;
	#define _idct_arg_type_input dsx_mwmr_t;
	dsx_mwmr_t output;
	#define _idct_arg_type_output dsx_mwmr_t;

	/* Just to avoid empty arg list */
	int is_unused;
};

#ifndef DSX_INMAIN

#define GET_ARG(port) ({ \
dsx_log_printf( TRACE, "%s:%d: arg %s = %p\n", __FILE__, __LINE__, #port, _func_args->port ); \
/* (_idct_arg_type_ ## port)(_func_args->port)); */ \
(_func_args->port); \
})

typedef void idct_func_t(idct_args_t*);

#define FUNC(sym) void idct_func_ ## sym(idct_args_t *_func_args)

/* Forward declarations, to enforce types */

idct_func_t idct_func_idct;


#else /* is DSX_INMAIN */
/* Declaration of launcher */
pthread_t idct_launcher( idct_args_t *);
#endif /* DSX_INMAIN */

#endif /* _IDCT_PROTO_H */
