
/**
 ** Auto-generated file, dont modify directly
 ** your changes will be lost !
 **
 ** Generated by DSX on 2006-04-12 16:13:48.074916
 ** by unknown@callisto
 **/
#ifndef _IQZZ_PROTO_H
#define _IQZZ_PROTO_H

#include <dsx.h>

typedef struct _iqzz_args_t iqzz_args_t;
struct _iqzz_args_t {
	dsx_mwmr_t input;
	#define _iqzz_arg_type_input dsx_mwmr_t;
	dsx_mwmr_t quanti;
	#define _iqzz_arg_type_quanti dsx_mwmr_t;
	dsx_mwmr_t output;
	#define _iqzz_arg_type_output dsx_mwmr_t;

	/* Just to avoid empty arg list */
	int is_unused;
};

#ifndef DSX_INMAIN

#define GET_ARG(port) ({ \
dsx_log_printf( TRACE, "%s:%d: arg %s = %p\n", __FILE__, __LINE__, #port, _func_args->port ); \
/* (_iqzz_arg_type_ ## port)(_func_args->port)); */ \
(_func_args->port); \
})

typedef void iqzz_func_t(iqzz_args_t*);

#define FUNC(sym) void iqzz_func_ ## sym(iqzz_args_t *_func_args)

/* Forward declarations, to enforce types */

iqzz_func_t iqzz_func_iqzz;


#else /* is DSX_INMAIN */
/* Declaration of launcher */
pthread_t iqzz_launcher( iqzz_args_t * );
#endif /* DSX_INMAIN */

#endif /* _IQZZ_PROTO_H */
