
/**
 ** Auto-generated file, dont modify directly
 ** your changes will be lost !
 **
 ** Generated by DSX on 2006-04-12 16:13:48.076240
 ** by unknown@callisto
 **/
#ifndef _LIBU_PROTO_H
#define _LIBU_PROTO_H

#include <dsx.h>

typedef struct _libu_args_t libu_args_t;
struct _libu_args_t {
	dsx_mwmr_t input;
	#define _libu_arg_type_input dsx_mwmr_t;
	dsx_mwmr_t output;
	#define _libu_arg_type_output dsx_mwmr_t;

	/* Just to avoid empty arg list */
	int is_unused;
};

#ifndef DSX_INMAIN

#define GET_ARG(port) ({ \
dsx_log_printf( TRACE, "%s:%d: arg %s = %p\n", __FILE__, __LINE__, #port, _func_args->port ); \
/* (_libu_arg_type_ ## port)(_func_args->port)); */ \
(_func_args->port); \
})

typedef void libu_func_t(libu_args_t*);

#define FUNC(sym) void libu_func_ ## sym(libu_args_t *_func_args)

/* Forward declarations, to enforce types */

libu_func_t libu_func_libu;


#else /* is DSX_INMAIN */
/* Declaration of launcher */
pthread_t libu_launcher( libu_args_t * );
#endif /* DSX_INMAIN */

#endif /* _LIBU_PROTO_H */
