
/**
 ** Auto-generated file, dont modify directly
 ** your changes will be lost !
 **
 ** Generated by DSX on 2006-04-12 16:13:48.076898
 ** by unknown@callisto
 **/
#ifndef _RAMDAC_PROTO_H
#define _RAMDAC_PROTO_H

#include <dsx.h>

typedef struct _ramdac_args_t ramdac_args_t;
struct _ramdac_args_t {
	dsx_mwmr_t input;
	#define _ramdac_arg_type_input dsx_mwmr_t;

	/* Just to avoid empty arg list */
	int is_unused;
};

#ifndef DSX_INMAIN

#define GET_ARG(port) ({ \
dsx_log_printf( TRACE, "%s:%d: arg %s = %p\n", __FILE__, __LINE__, #port, _func_args->port ); \
/* (_ramdac_arg_type_ ## port)(_func_args->port)); */ \
(_func_args->port); \
})

typedef void ramdac_func_t(ramdac_args_t*);

#define FUNC(sym) void ramdac_func_ ## sym(ramdac_args_t *_func_args)

/* Forward declarations, to enforce types */

ramdac_func_t ramdac_func_ramdac;


#else /* is DSX_INMAIN */
/* Declaration of launcher */
pthread_t ramdac_launcher( ramdac_args_t * );
#endif /* DSX_INMAIN */

#endif /* _RAMDAC_PROTO_H */
