
/**
 ** Auto-generated file, dont modify directly
 ** your changes will be lost !
 **
 ** Generated by DSX on 2006-04-12 16:13:48.072622
 ** by unknown@callisto
 **/
#ifndef _TG_PROTO_H
#define _TG_PROTO_H

#include <dsx.h>

typedef struct _tg_args_t tg_args_t;
struct _tg_args_t {
	dsx_mwmr_t output;
	#define _tg_arg_type_output dsx_mwmr_t;

	/* Just to avoid empty arg list */
	int is_unused;
};

#ifndef DSX_INMAIN

#define GET_ARG(port) ({ \
dsx_log_printf( TRACE, "%s:%d: arg %s = %p\n", __FILE__, __LINE__, #port, _func_args->port ); \
/* (_tg_arg_type_ ## port)(_func_args->port)); */ \
(_func_args->port); \
})

typedef void tg_func_t(tg_args_t*);

#define FUNC(sym) void tg_func_ ## sym(tg_args_t *_func_args)

/* Forward declarations, to enforce types */

tg_func_t tg_func_tg;


#else /* is DSX_INMAIN */
/* Declaration of launcher */
pthread_t tg_launcher( tg_args_t * );
#endif /* DSX_INMAIN */

#endif /* _TG_PROTO_H */
