
/**
 ** Auto-generated file, dont modify directly
 ** your changes will be lost !
 **
 ** Generated by DSX on 2006-04-12 16:13:48.074231
 ** by unknown@callisto
 **/
#ifndef _VLD_PROTO_H
#define _VLD_PROTO_H

#include <dsx.h>

typedef struct _vld_args_t vld_args_t;
struct _vld_args_t {
	dsx_mwmr_t input;
	#define _vld_arg_type_input dsx_mwmr_t;
	dsx_mwmr_t huffman;
	#define _vld_arg_type_huffman dsx_mwmr_t;
	dsx_mwmr_t output;
	#define _vld_arg_type_output dsx_mwmr_t;

	/* Just to avoid empty arg list */
	int is_unused;
};

#ifndef DSX_INMAIN

#define GET_ARG(port) ({ \
dsx_log_printf( TRACE, "%s:%d: arg %s = %p\n", __FILE__, __LINE__, #port, _func_args->port ); \
/* (_vld_arg_type_ ## port)(_func_args->port)); */ \
(_func_args->port); \
})

typedef void vld_func_t(vld_args_t*);

#define FUNC(sym) void vld_func_ ## sym(vld_args_t *_func_args)

/* Forward declarations, to enforce types */

vld_func_t vld_func_vld;


#else /* is DSX_INMAIN */
/* Declaration of launcher */
pthread_t vld_launcher( vld_args_t * );
#endif /* DSX_INMAIN */

#endif /* _VLD_PROTO_H */
