
/**
 ** Auto-generated file, dont modify directly
 ** your changes will be lost !
 **
 ** Generated by DSX on 2006-04-12 16:13:48.073838
 ** by unknown@callisto
 **/

#include <libc.h>
#include "pthread.h"
#include "demux_proto.h"

struct thargs {
	pthread_t thread;
	demux_args_t *args;
};

extern pthread_barrier_t	barrier;

static void* demux_thread( void *_args )
{
	struct thargs *args = _args;

	printf("demux ready!\n");

	pthread_barrier_wait(&barrier);

	while(1)
	  demux_func_demux( args->args );
	return NULL;
}

pthread_t demux_launcher( demux_args_t *args )
{
  static struct thargs thargs;
  thargs.args = args;
  pthread_create( &(thargs.thread), NULL, demux_thread, &thargs );
  return thargs.thread;
}
