
/**
 ** Auto-generated file, dont modify directly
 ** your changes will be lost !
 **
 ** Generated by DSX on 2006-04-12 16:13:48.075870
 ** by unknown@callisto
 **/

#include <libc.h>
#include "pthread.h"
#include "idct_proto.h"

struct thargs {
	pthread_t thread;
	idct_args_t *args;
};

extern pthread_barrier_t	barrier;

static void* idct_thread( void *_args )
{
	struct thargs *args = _args;

	printf("idct ready!\n");

	pthread_barrier_wait(&barrier);

	while(1)
	  idct_func_idct( args->args );
	return NULL;
}

pthread_t idct_launcher( idct_args_t *args )
{
  static struct thargs thargs;
  thargs.args = args;
  pthread_create( &(thargs.thread), NULL, idct_thread, &thargs );
  return thargs.thread;
}
