
/**
 ** Auto-generated file, dont modify directly
 ** your changes will be lost !
 **
 ** Generated by DSX on 2006-04-12 16:13:48.075206
 ** by unknown@callisto
 **/

#include <libc.h>
#include "pthread.h"
#include "iqzz_proto.h"

struct thargs {
	pthread_t thread;
	iqzz_args_t *args;
};

extern pthread_barrier_t	barrier;

static void* iqzz_thread( void *_args )
{
	struct thargs *args = _args;

	printf("iqzz ready!\n");

	pthread_barrier_wait(&barrier);

	while(1)
	  iqzz_func_iqzz( args->args );
	return NULL;
}

pthread_t iqzz_launcher( iqzz_args_t *args )
{
  static struct thargs thargs;
  thargs.args = args;
  pthread_create( &(thargs.thread), NULL, iqzz_thread, &thargs );
  return thargs.thread;
}
