
/**
 ** Auto-generated file, dont modify directly
 ** your changes will be lost !
 **
 ** Generated by DSX on 2006-04-12 16:13:48.076525
 ** by unknown@callisto
 **/

#include <libc.h>
#include "pthread.h"
#include "libu_proto.h"

struct thargs {
	pthread_t thread;
	libu_args_t *args;
};

extern pthread_barrier_t	barrier;

static void* libu_thread( void *_args )
{
	struct thargs *args = _args;

	printf("libu ready\n");

	pthread_barrier_wait(&barrier);

	while(1)
	  libu_func_libu( args->args );
	return NULL;
}

pthread_t libu_launcher( libu_args_t *args )
{
  static struct thargs thargs;
  thargs.args = args;
  pthread_create( &(thargs.thread), NULL, libu_thread, &thargs );
  return thargs.thread;
}
