
/**
 ** Auto-generated file, dont modify directly
 ** your changes will be lost !
 **
 ** Generated by DSX on 2006-04-12 16:13:48.077966
 ** by unknown@callisto
 **/

#include <libc.h>
#include <crt.h>

#include <dsx.h>
#define DSX_INMAIN
#include "tg_proto.h"
#include "demux_proto.h"
#include "vld_proto.h"
#include "iqzz_proto.h"
#include "idct_proto.h"
#include "libu_proto.h"
#include "ramdac_proto.h"

#define VGA_SPAWN_INTERFACE
#define VGA_INLINE_INTERFACE
#include "../../drivers/vga/vga-driver.h"
#define MOD_SPAWN_INTERFACE
#define MOD_INLINE_INTERFACE
#include "../../services/mod/mod-service.h"

unsigned char *framebuffer;
pthread_barrier_t	barrier;

int	main()
{
  static struct _mwmr_t tg_demux;
  static struct _mwmr_t quanti;
  static struct _mwmr_t vld_iqzz;
  static struct _mwmr_t demux_vld;
  static struct _mwmr_t huffman;
  static struct _mwmr_t iqzz_idct;
  static struct _mwmr_t idct_libu;
  static struct _mwmr_t libu_ramdac;

  pthread_t		tg;
  pthread_t		vld;
  pthread_t		demux;
  pthread_t		iqzz;
  pthread_t		idct;
  pthread_t		libu;
  pthread_t		ramdac;

  i_thread		th;
  i_task		vga;

  printf("MJPEG test application...\n");

  for (th = 0; th < 100; th++)
    scheduler_yield(0);

  if (vga_init() != ERROR_NONE)
    {
      printf("vga_init failed.\n");
      return (-1);
    }

  if (mod_get_service(_crt_get_mod_id(), "vga", &vga) != ERROR_NONE)
    {
      printf("cannot get vga driver.\n");
      return (-1);
    }

  if (0 && vga_framebuffer(vga, 320, 200, 8, (t_vaddr*)&framebuffer) != ERROR_NONE ||
      framebuffer == ((t_vaddr)-1))
    {
      printf("cannot start vga framebuffer.\n");
      return (-1);
    }

  //memset(framebuffer, 0x0, 64000);

  dsx_mwmr_alloc(&tg_demux, 8, 2, "tg_demux");
  dsx_mwmr_alloc(&quanti, 8, 4, "quanti");
  dsx_mwmr_alloc(&vld_iqzz, 32, 2, "vld_iqzz");
  dsx_mwmr_alloc(&demux_vld, 8, 2, "demux_vld");
  dsx_mwmr_alloc(&huffman, 8, 6, "huffman");
  dsx_mwmr_alloc(&iqzz_idct, 64, 2, "iqzz_idct");
  dsx_mwmr_alloc(&idct_libu, 16, 2, "idct_libu");
  dsx_mwmr_alloc(&libu_ramdac, 96, 2, "libu_ramdac");

  pthread_barrier_init(&barrier, NULL, 7);

  static tg_args_t tg_args = {
    .output = &tg_demux,
    .is_unused = 42
  };
  tg = tg_launcher( &tg_args );


  static demux_args_t demux_args = {
    .input = &tg_demux,
    .quanti = &quanti,
    .huffman = &huffman,
    .output = &demux_vld,
    .is_unused = 42
  };
  demux = demux_launcher( &demux_args );


  static vld_args_t vld_args = {
    .input = &demux_vld,
    .huffman = &huffman,
    .output = &vld_iqzz,
    .is_unused = 42
  };
  vld = vld_launcher( &vld_args );


  static iqzz_args_t iqzz_args = {
    .input = &vld_iqzz,
    .quanti = &quanti,
    .output = &iqzz_idct,
    .is_unused = 42
  };
  iqzz = iqzz_launcher( &iqzz_args );


  static idct_args_t idct_args = {
    .input = &iqzz_idct,
    .output = &idct_libu,
    .is_unused = 42
  };
  idct = idct_launcher( &idct_args );


  static libu_args_t libu_args = {
    .input = &idct_libu,
    .output = &libu_ramdac,
    .is_unused = 42
  };
  libu = libu_launcher( &libu_args );


  static ramdac_args_t ramdac_args = {
    .input = &libu_ramdac,
    .is_unused = 42
  };
  ramdac = ramdac_launcher( &ramdac_args );

  while (0)
    {
      scheduler_current(&th);

      printf("th = %qd\n", th);

      if (th > 15)
	{
	  while (1)
	    ;
	}
    }

  if (scheduler_current(&th) == ERROR_NONE)
    {
      thread_state(th, SCHEDULER_STATE_STOP);
    }

  printf("!!!\n");

  while (1)
    ;
}
