
/**
 ** Auto-generated file, dont modify directly
 ** your changes will be lost !
 **
 ** Generated by DSX on 2006-04-12 16:13:48.077183
 ** by unknown@callisto
 **/

#include <libc.h>
#include "pthread.h"
#include "ramdac_proto.h"

struct thargs {
	pthread_t thread;
	ramdac_args_t *args;
};

extern pthread_barrier_t	barrier;

static void* ramdac_thread( void *_args )
{
	struct thargs *args = _args;

	printf("ramdac ready!\n");

	pthread_barrier_wait(&barrier);

	while(1)
	  ramdac_func_ramdac( args->args );
	return NULL;
}

pthread_t ramdac_launcher( ramdac_args_t *args )
{
  static struct thargs thargs;
  thargs.args = args;
  pthread_create( &(thargs.thread), NULL, ramdac_thread, &thargs );
  return thargs.thread;
}
