
/**
 ** Auto-generated file, dont modify directly
 ** your changes will be lost !
 **
 ** Generated by DSX on 2006-04-12 16:13:48.073838
 ** by unknown@callisto
 **/

#include <klibc.h>
#include "pthread.h"
#include "demux_proto.h"

struct thargs {
	pthread_t thread;
	demux_args_t *args;
};

static void* demux_thread( void *_args )
{
	struct thargs *args = _args;

	while(1)
	  demux_func_demux( args->args );
	return NULL;
}

void demux_launcher( demux_args_t *args )
{
	struct thargs *thargs = malloc(sizeof(struct thargs));
	thargs->args = args;
	pthread_create( &(thargs->thread), NULL, demux_thread, thargs );
}
