
/**
 ** Auto-generated file, dont modify directly
 ** your changes will be lost !
 **
 ** Generated by DSX on 2006-04-12 16:13:48.076525
 ** by unknown@callisto
 **/

#include <klibc.h>
#include "pthread.h"
#include "libu_proto.h"

struct thargs {
	pthread_t thread;
	libu_args_t *args;
};

static void* libu_thread( void *_args )
{
	struct thargs *args = _args;

	while(1)
	  libu_func_libu( args->args );
	return NULL;
}

void libu_launcher( libu_args_t *args )
{
	struct thargs *thargs = malloc(sizeof(struct thargs));
	thargs->args = args;
	pthread_create( &(thargs->thread), NULL, libu_thread, thargs );
}
