
/**
 ** Auto-generated file, dont modify directly
 ** your changes will be lost !
 **
 ** Generated by DSX on 2006-04-12 16:13:48.074520
 ** by unknown@callisto
 **/

#include <klibc.h>
#include "pthread.h"
#include "vld_proto.h"

struct thargs {
	pthread_t thread;
	vld_args_t *args;
};

static void* vld_thread( void *_args )
{
	struct thargs *args = _args;

	while(1)
	  vld_func_vld( args->args );
	return NULL;
}

void vld_launcher( vld_args_t *args )
{
  static struct thargs thargs;
  thargs.args = args;
  pthread_create( &(thargs.thread), NULL, vld_thread, &thargs );
}
