#
# ---------- header -----------------------------------------------------------
#
# project       kaneton
#
# license       kaneton
#
# file          /home/mycure/kaneton/view/bibliography/Makefile
#
# created       julien quintard   [wed may 16 18:33:46 2007]
# updated       julien quintard   [wed may 16 18:39:00 2007]
#

#
# ---------- dependencies -----------------------------------------------------
#

include			../../env/.env.mk

#
# ---------- directives -------------------------------------------------------
#

.PHONY:		all clear proto dep

#
# ---------- rules ------------------------------------------------------------
#

all:

clear:
	$(call purge)

proto:

dep:
