#
# ---------- header -----------------------------------------------------------
#
# project       kaneton
#
# license       kaneton
#
# file          /home/mycure/kaneton/boot/bootstrap/Makefile
#
# created       julien quintard   [tue jun 12 20:03:52 2007]
# updated       julien quintard   [tue jun 12 20:04:08 2007]
#

#
# ---------- dependencies -----------------------------------------------------
#

include			../../environment/env.mk

#
# ---------- directives -------------------------------------------------------
#

.PHONY:		main clear prototypes headers

#
# ---------- rules ------------------------------------------------------------
#

main:

clear:
	$(call env_purge,)

proto:

headers:
