#
# ---------- header -----------------------------------------------------------
#
# project       kaneton
#
# license       kaneton
#
# file          /home/mycure/kaneton/history/Makefile
#
# created       julien quintard   [sun jun 10 14:53:00 2007]
# updated       julien quintard   [wed apr 22 12:21:12 2009]
#

#
# ---------- dependencies -----------------------------------------------------
#

include			../environment/env.mk

#
# ---------- directives -------------------------------------------------------
#

.PHONY:		main clear prototypes headers

#
# ---------- rules ------------------------------------------------------------
#

main:

clear:
	$(call env_purge)

prototypes:

headers:
