##
## licence       kaneton licence
##
## project       kaneton
##
## file          /home/mycure/kaneton/view/internships/Makefile
##
## created       renaud voltz   [thu feb  9 02:37:29 2006]
## updated       julien quintard   [thu jul 13 11:45:45 2006]
##

#
# ---------- dependencies -----------------------------------------------------
#

include			../../env/.env.mk

#
# ---------- directives -------------------------------------------------------
#

.PHONY:		all clear proto dep

#
# ---------- variables --------------------------------------------------------
#

SUBDIRS			:=		check

#
# ---------- rules ------------------------------------------------------------
#

all:
	$(call launch,Makefile,$(SUBDIRS),,)

clear:
	$(call launch,Makefile,$(SUBDIRS),clear,)

	$(call purge)

proto:

dep:
