#
# ---------- header -----------------------------------------------------------
#
# project       kaneton
#
# license       kaneton
#
# file          /home/mycure/kaneton/view/feedback/kernels/Makefile
#
# created       julien quintard   [tue may 15 21:52:06 2007]
# updated       julien quintard   [thu may  7 12:50:28 2009]
#

#
# ---------- dependencies -----------------------------------------------------
#

include			../../../environment/env.mk

#
# ---------- directives -------------------------------------------------------
#

.PHONY:		main view build clear

#
# ---------- variables --------------------------------------------------------
#

PAPER			:=		kernels

SOURCES			:=		kernels.tex

#
# ---------- rules ------------------------------------------------------------
#

main:			build

view:			build

build:

clear:
	$(call env_remove,$(_DEPENDENCY_TEX_),)

	$(call env_purge)
