##
## copyright quintard julien
## 
## kaneton
## 
## Makefile
## 
## path          /home/mycure/kaneton/conf
## 
## made by mycure
##         quintard julien   [quinta_j@epita.fr]
## 
## started on    Fri Feb 11 02:59:20 2005   mycure
## last update   Tue Oct 25 03:48:23 2005   mycure
##

#
# ---------- dependencies -----------------------------------------------------
#

include			../.kaneton.mk

#
# ---------- directives -------------------------------------------------------
#

.PHONY:		all clear proto dep

#
# ---------- variables --------------------------------------------------------
#

KANETON_CONF		:=		kaneton.conf

#
# ---------- rules ------------------------------------------------------------
#

all:

clear:
	$(call remove,$(KANETON_CONF),)

	$(call purge)

proto:

dep:
