#
# ---------- header -----------------------------------------------------------
#
# project       kaneton
#
# license       kaneton
#
# file          /home/mycure/kane...view/lecture/architectures/ia32/Makefile
#
# created       julien quintard   [wed may 16 18:08:19 2007]
# updated       julien quintard   [mon jun 11 07:27:22 2007]
#

#
# ---------- dependencies -----------------------------------------------------
#

include			../../../../environment/env.mk

#
# ---------- directives -------------------------------------------------------
#

.PHONY:		main clear

#
# ---------- rules ------------------------------------------------------------
#

main:

clear:
	$(call env_purge)
