##
## ---------- header ----------------------------------------------------------
##
## project       kaneton
##
## license       kaneton
##
## file          /home/mycure/kaneton/libs/libsun4u/Makefile
##
## created       julien quintard   [sat oct 14 10:30:38 2006]
## updated       julien quintard   [sat oct 14 11:12:32 2006]
##

all:

clear:

proto:

dep:
