##
## kaneton
## 
## Makefile
## 
## path          /home/mycure/kaneton/papers/lectures/c-preprocessor
## 
## made by mycure
##         quintard julien   [quinta_j@epita.fr]
## 
## started on    Sun Nov 21 14:13:54 2004   mycure
## last update   Wed Sep  7 11:04:32 2005   mycure
##

#
# file
#

_FILE_			:=		c-preprocessor

#
# dependency
#

include			../../makefile.mk
