ctype.o: ctype.c /home/vertrex/kaneton/libs/klibc/include/klibc.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/types.h \
  /home/vertrex/kaneton/core/include/arch/machdep/machdep.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/ia32.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/asm.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/multiboot.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/paging.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/types.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/pmode.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/stdarg.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/kaneton.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/bootloader.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/cons.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/debug.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/init.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/services.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/sys.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/elf.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/printf.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/errno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/limits.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/services.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/quad.h
bcmp.o: bcmp.c /home/vertrex/kaneton/libs/klibc/include/klibc.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/types.h \
  /home/vertrex/kaneton/core/include/arch/machdep/machdep.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/ia32.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/asm.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/multiboot.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/paging.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/types.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/pmode.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/stdarg.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/kaneton.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/bootloader.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/cons.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/debug.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/init.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/services.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/sys.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/elf.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/printf.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/errno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/limits.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/services.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/quad.h
bcopy.o: bcopy.c /home/vertrex/kaneton/libs/klibc/include/klibc.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/types.h \
  /home/vertrex/kaneton/core/include/arch/machdep/machdep.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/ia32.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/asm.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/multiboot.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/paging.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/types.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/pmode.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/stdarg.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/kaneton.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/bootloader.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/cons.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/debug.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/init.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/services.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/sys.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/elf.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/printf.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/errno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/limits.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/services.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/quad.h
bzero.o: bzero.c /home/vertrex/kaneton/libs/klibc/include/klibc.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/types.h \
  /home/vertrex/kaneton/core/include/arch/machdep/machdep.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/ia32.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/asm.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/multiboot.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/paging.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/types.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/pmode.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/stdarg.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/kaneton.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/bootloader.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/cons.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/debug.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/init.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/services.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/sys.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/elf.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/printf.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/errno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/limits.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/services.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/quad.h
index.o: index.c /home/vertrex/kaneton/libs/klibc/include/klibc.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/types.h \
  /home/vertrex/kaneton/core/include/arch/machdep/machdep.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/ia32.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/asm.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/multiboot.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/paging.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/types.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/pmode.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/stdarg.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/kaneton.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/bootloader.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/cons.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/debug.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/init.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/services.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/sys.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/elf.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/printf.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/errno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/limits.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/services.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/quad.h
memcmp.o: memcmp.c /home/vertrex/kaneton/libs/klibc/include/klibc.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/types.h \
  /home/vertrex/kaneton/core/include/arch/machdep/machdep.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/ia32.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/asm.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/multiboot.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/paging.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/types.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/pmode.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/stdarg.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/kaneton.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/bootloader.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/cons.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/debug.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/init.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/services.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/sys.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/elf.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/printf.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/errno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/limits.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/services.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/quad.h
memcpy.o: memcpy.c /home/vertrex/kaneton/libs/klibc/include/klibc.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/types.h \
  /home/vertrex/kaneton/core/include/arch/machdep/machdep.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/ia32.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/asm.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/multiboot.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/paging.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/types.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/pmode.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/stdarg.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/kaneton.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/bootloader.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/cons.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/debug.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/init.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/services.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/sys.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/elf.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/printf.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/errno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/limits.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/services.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/quad.h
memset.o: memset.c /home/vertrex/kaneton/libs/klibc/include/klibc.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/types.h \
  /home/vertrex/kaneton/core/include/arch/machdep/machdep.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/ia32.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/asm.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/multiboot.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/paging.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/types.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/pmode.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/stdarg.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/kaneton.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/bootloader.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/cons.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/debug.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/init.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/services.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/sys.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/elf.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/printf.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/errno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/limits.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/services.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/quad.h
printf.o: printf.c \
  /home/vertrex/kaneton/core/include/arch/machdep/machdep.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/ia32.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/asm.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/multiboot.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/paging.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/types.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/pmode.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/stdarg.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/kaneton.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/bootloader.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/cons.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/debug.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/init.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/services.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/sys.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/elf.h \
  /home/vertrex/kaneton/libs/klibc/include/klibc.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/types.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/printf.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/errno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/limits.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/services.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/quad.h
rindex.o: rindex.c /home/vertrex/kaneton/libs/klibc/include/klibc.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/types.h \
  /home/vertrex/kaneton/core/include/arch/machdep/machdep.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/ia32.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/asm.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/multiboot.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/paging.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/types.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/pmode.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/stdarg.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/kaneton.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/bootloader.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/cons.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/debug.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/init.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/services.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/sys.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/elf.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/printf.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/errno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/limits.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/services.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/quad.h
strcat.o: strcat.c /home/vertrex/kaneton/libs/klibc/include/klibc.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/types.h \
  /home/vertrex/kaneton/core/include/arch/machdep/machdep.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/ia32.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/asm.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/multiboot.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/paging.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/types.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/pmode.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/stdarg.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/kaneton.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/bootloader.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/cons.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/debug.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/init.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/services.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/sys.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/elf.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/printf.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/errno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/limits.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/services.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/quad.h
strchr.o: strchr.c /home/vertrex/kaneton/libs/klibc/include/klibc.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/types.h \
  /home/vertrex/kaneton/core/include/arch/machdep/machdep.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/ia32.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/asm.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/multiboot.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/paging.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/types.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/pmode.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/stdarg.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/kaneton.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/bootloader.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/cons.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/debug.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/init.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/services.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/sys.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/elf.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/printf.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/errno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/limits.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/services.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/quad.h
strcmp.o: strcmp.c /home/vertrex/kaneton/libs/klibc/include/klibc.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/types.h \
  /home/vertrex/kaneton/core/include/arch/machdep/machdep.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/ia32.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/asm.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/multiboot.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/paging.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/types.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/pmode.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/stdarg.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/kaneton.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/bootloader.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/cons.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/debug.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/init.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/services.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/sys.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/elf.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/printf.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/errno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/limits.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/services.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/quad.h
strcpy.o: strcpy.c /home/vertrex/kaneton/libs/klibc/include/klibc.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/types.h \
  /home/vertrex/kaneton/core/include/arch/machdep/machdep.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/ia32.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/asm.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/multiboot.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/paging.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/types.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/pmode.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/stdarg.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/kaneton.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/bootloader.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/cons.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/debug.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/init.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/services.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/sys.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/elf.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/printf.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/errno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/limits.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/services.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/quad.h
strlen.o: strlen.c /home/vertrex/kaneton/libs/klibc/include/klibc.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/types.h \
  /home/vertrex/kaneton/core/include/arch/machdep/machdep.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/ia32.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/asm.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/multiboot.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/paging.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/types.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/pmode.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/stdarg.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/kaneton.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/bootloader.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/cons.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/debug.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/init.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/services.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/sys.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/elf.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/printf.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/errno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/limits.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/services.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/quad.h
strncat.o: strncat.c /home/vertrex/kaneton/libs/klibc/include/klibc.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/types.h \
  /home/vertrex/kaneton/core/include/arch/machdep/machdep.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/ia32.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/asm.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/multiboot.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/paging.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/types.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/pmode.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/stdarg.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/kaneton.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/bootloader.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/cons.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/debug.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/init.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/services.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/sys.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/elf.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/printf.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/errno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/limits.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/services.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/quad.h
strncmp.o: strncmp.c /home/vertrex/kaneton/libs/klibc/include/klibc.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/types.h \
  /home/vertrex/kaneton/core/include/arch/machdep/machdep.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/ia32.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/asm.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/multiboot.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/paging.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/types.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/pmode.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/stdarg.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/kaneton.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/bootloader.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/cons.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/debug.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/init.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/services.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/sys.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/elf.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/printf.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/errno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/limits.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/services.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/quad.h
strncpy.o: strncpy.c /home/vertrex/kaneton/libs/klibc/include/klibc.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/types.h \
  /home/vertrex/kaneton/core/include/arch/machdep/machdep.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/ia32.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/asm.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/multiboot.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/paging.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/types.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/pmode.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/stdarg.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/kaneton.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/bootloader.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/cons.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/debug.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/init.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/services.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/sys.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/elf.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/printf.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/errno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/limits.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/services.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/quad.h
strtol.o: strtol.c /home/vertrex/kaneton/libs/klibc/include/klibc.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/types.h \
  /home/vertrex/kaneton/core/include/arch/machdep/machdep.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/ia32.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/asm.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/multiboot.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/paging.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/types.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/pmode.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/stdarg.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/kaneton.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/bootloader.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/cons.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/debug.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/init.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/services.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/sys.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/elf.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/printf.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/errno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/limits.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/services.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/quad.h
strtoul.o: strtoul.c /home/vertrex/kaneton/libs/klibc/include/klibc.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/types.h \
  /home/vertrex/kaneton/core/include/arch/machdep/machdep.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/ia32.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/asm.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/multiboot.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/paging.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/types.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/pmode.h \
  /home/vertrex/kaneton/core/include/arch/ia32/ia32/stdarg.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/kaneton.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/bootloader.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/cons.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/debug.h \
  /home/vertrex/kaneton/core/include/arch/ia32/kaneton/init.h \
  /home/vertrex/kaneton/core/include/arch/ia32/services/services.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/sys.h \
  /home/vertrex/kaneton/core/include/arch/ia32/sys/elf.h \
  /home/vertrex/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/vertrex/kaneton/libs/klibc/include/libstring/printf.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/errno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/limits.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/services.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/vertrex/kaneton/libs/klibc/include/libsys/quad.h
