#
# ---------- header -----------------------------------------------------------
#
# project       kaneton
#
# license       kaneton
#
# file          /home/mycure/kaneton/view/package/Makefile
#
# created       julien quintard   [wed may 16 18:08:19 2007]
# updated       julien quintard   [sat jun  9 23:39:00 2007]
#

#
# ---------- dependencies -----------------------------------------------------
#

include			../../environment/env.mk

#
# ---------- directives -------------------------------------------------------
#

.PHONY:		main build clear

#
# ---------- rules ------------------------------------------------------------
#

main:

build:

clear:
	$(call purge)
