kaneton.o: kaneton.c /home/mycure/kaneton/libs/libc.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/types.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/errno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/limits.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/services.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/quad.h \
  /home/mycure/kaneton/core/include/arch/machdep/machdep.h \
  /home/mycure/kaneton/core/include/arch/machdep/asm.h \
  /home/mycure/kaneton/core/include/arch/machdep/stdarg.h \
  /home/mycure/kaneton/core/include/arch/machdep/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/multiboot.h \
  /home/mycure/kaneton/core/include/arch/machdep/elf.h \
  /home/mycure/kaneton/core/include/arch/machdep/kaneton.h \
  /home/mycure/kaneton/core/include/arch/machdep/init.h \
  /home/mycure/kaneton/core/include/arch/machdep/cons.h \
  /home/mycure/kaneton/core/include/arch/machdep/pmode.h \
  /home/mycure/kaneton/core/include/arch/machdep/paging.h \
  /home/mycure/kaneton/core/include/arch/machdep/bootloader.h \
  /home/mycure/kaneton/libs/klibc/include/libc/libc.h \
  /home/mycure/kaneton/libs/klibc/include/libc/ctype.h \
  /home/mycure/kaneton/libs/klibc/include/libc/printf.h \
  /home/mycure/kaneton/core/include/kaneton.h \
  /home/mycure/kaneton/core/include/version.h \
  /home/mycure/kaneton/core/include/kaneton/kaneton.h \
  /home/mycure/kaneton/core/include/kaneton/init.h \
  /home/mycure/kaneton/core/include/kaneton/segment.h \
  /home/mycure/kaneton/core/include/kaneton/errno.h \
  /home/mycure/kaneton/core/include/kaneton/suberrno.h \
  /home/mycure/kaneton/core/include/sys/sys.h \
  /home/mycure/kaneton/core/include/sys/elf.h
cons.o: cons.c /home/mycure/kaneton/libs/libc.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/types.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/errno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/limits.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/services.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/quad.h \
  /home/mycure/kaneton/core/include/arch/machdep/machdep.h \
  /home/mycure/kaneton/core/include/arch/machdep/asm.h \
  /home/mycure/kaneton/core/include/arch/machdep/stdarg.h \
  /home/mycure/kaneton/core/include/arch/machdep/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/multiboot.h \
  /home/mycure/kaneton/core/include/arch/machdep/elf.h \
  /home/mycure/kaneton/core/include/arch/machdep/kaneton.h \
  /home/mycure/kaneton/core/include/arch/machdep/init.h \
  /home/mycure/kaneton/core/include/arch/machdep/cons.h \
  /home/mycure/kaneton/core/include/arch/machdep/pmode.h \
  /home/mycure/kaneton/core/include/arch/machdep/paging.h \
  /home/mycure/kaneton/core/include/arch/machdep/bootloader.h \
  /home/mycure/kaneton/libs/klibc/include/libc/libc.h \
  /home/mycure/kaneton/libs/klibc/include/libc/ctype.h \
  /home/mycure/kaneton/libs/klibc/include/libc/printf.h \
  /home/mycure/kaneton/core/include/kaneton.h \
  /home/mycure/kaneton/core/include/version.h \
  /home/mycure/kaneton/core/include/kaneton/kaneton.h \
  /home/mycure/kaneton/core/include/kaneton/init.h \
  /home/mycure/kaneton/core/include/kaneton/segment.h \
  /home/mycure/kaneton/core/include/kaneton/errno.h \
  /home/mycure/kaneton/core/include/kaneton/suberrno.h \
  /home/mycure/kaneton/core/include/sys/sys.h \
  /home/mycure/kaneton/core/include/sys/elf.h
