as.o: as.c /home/buckman/kaneton/libs/klibc/include/klibc.h \
  /home/buckman/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/types.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/machdep.h \
  /home/buckman/kaneton/libs/libia32/include/libia32.h \
  /home/buckman/kaneton/libs/libia32/include/misc/asm.h \
  /home/buckman/kaneton/libs/libia32/include/misc/isa.h \
  /home/buckman/kaneton/libs/libia32/include/misc/multiboot.h \
  /home/buckman/kaneton/libs/libia32/include/misc/stdarg.h \
  /home/buckman/kaneton/libs/libia32/include/misc/types.h \
  /home/buckman/kaneton/kaneton/include/core/types.h \
  /home/buckman/kaneton/libs/libia32/include/misc/spinlock.h \
  /home/buckman/kaneton/libs/libia32/include/paging/paging.h \
  /home/buckman/kaneton/libs/libia32/include/paging/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/pmode.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/gdt.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/idt.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/interrupt.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/pic.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/ipi.h \
  /home/buckman/kaneton/libs/libia32/include/time/pit.h \
  /home/buckman/kaneton/libs/libia32/include/task/context.h \
  /home/buckman/kaneton/libs/libia32/include/task/tss.h \
  /home/buckman/kaneton/libs/libia32/include/apic/apic.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/core.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/as.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/debug.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/init.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/services/cons.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/region.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/segment.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/stats.h \
  /home/buckman/kaneton/kaneton/include/core/stats.h \
  /home/buckman/kaneton/kaneton/include/core/id.h \
  /home/buckman/kaneton/kaneton/include/core/conf.h \
  /home/buckman/kaneton/kaneton/include/core/debug.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/event.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/timer.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/thread.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/task.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/sched.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/message.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/cpu.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/io.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/services/services.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/sys/sys.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/sys/elf.h \
  /home/buckman/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/printf.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/errno.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/limits.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/services.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/quad.h \
  /home/buckman/kaneton/kaneton/include/kaneton.h \
  /home/buckman/kaneton/kaneton/include/core/core.h \
  /home/buckman/kaneton/kaneton/include/core/as.h \
  /home/buckman/kaneton/kaneton/include/core/serial.h \
  /home/buckman/kaneton/kaneton/include/core/error.h \
  /home/buckman/kaneton/kaneton/include/core/kernel.h \
  /home/buckman/kaneton/kaneton/include/core/init.h \
  /home/buckman/kaneton/kaneton/include/core/segment.h \
  /home/buckman/kaneton/kaneton/include/core/region.h \
  /home/buckman/kaneton/kaneton/include/core/cpu.h \
  /home/buckman/kaneton/kaneton/include/core/map.h \
  /home/buckman/kaneton/kaneton/include/core/set.h \
  /home/buckman/kaneton/kaneton/include/core/set-array.h \
  /home/buckman/kaneton/kaneton/include/core/set-bpt.h \
  /home/buckman/kaneton/kaneton/include/sys/bpt.h \
  /home/buckman/kaneton/kaneton/include/core/set-ll.h \
  /home/buckman/kaneton/kaneton/include/core/event.h \
  /home/buckman/kaneton/kaneton/include/core/timer.h \
  /home/buckman/kaneton/kaneton/include/core/thread.h \
  /home/buckman/kaneton/kaneton/include/core/wait.h \
  /home/buckman/kaneton/kaneton/include/core/task.h \
  /home/buckman/kaneton/kaneton/include/core/sched.h \
  /home/buckman/kaneton/kaneton/include/core/message.h \
  /home/buckman/kaneton/kaneton/include/core/capability.h \
  /home/buckman/kaneton/kaneton/include/core/interface.h \
  /home/buckman/kaneton/kaneton/include/core/io.h \
  /home/buckman/kaneton/kaneton/include/sys/sys.h \
  /home/buckman/kaneton/kaneton/include/sys/elf.h
region.o: region.c /home/buckman/kaneton/libs/klibc/include/klibc.h \
  /home/buckman/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/types.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/machdep.h \
  /home/buckman/kaneton/libs/libia32/include/libia32.h \
  /home/buckman/kaneton/libs/libia32/include/misc/asm.h \
  /home/buckman/kaneton/libs/libia32/include/misc/isa.h \
  /home/buckman/kaneton/libs/libia32/include/misc/multiboot.h \
  /home/buckman/kaneton/libs/libia32/include/misc/stdarg.h \
  /home/buckman/kaneton/libs/libia32/include/misc/types.h \
  /home/buckman/kaneton/kaneton/include/core/types.h \
  /home/buckman/kaneton/libs/libia32/include/misc/spinlock.h \
  /home/buckman/kaneton/libs/libia32/include/paging/paging.h \
  /home/buckman/kaneton/libs/libia32/include/paging/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/pmode.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/gdt.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/idt.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/interrupt.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/pic.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/ipi.h \
  /home/buckman/kaneton/libs/libia32/include/time/pit.h \
  /home/buckman/kaneton/libs/libia32/include/task/context.h \
  /home/buckman/kaneton/libs/libia32/include/task/tss.h \
  /home/buckman/kaneton/libs/libia32/include/apic/apic.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/core.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/as.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/debug.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/init.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/services/cons.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/region.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/segment.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/stats.h \
  /home/buckman/kaneton/kaneton/include/core/stats.h \
  /home/buckman/kaneton/kaneton/include/core/id.h \
  /home/buckman/kaneton/kaneton/include/core/conf.h \
  /home/buckman/kaneton/kaneton/include/core/debug.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/event.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/timer.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/thread.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/task.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/sched.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/message.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/cpu.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/io.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/services/services.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/sys/sys.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/sys/elf.h \
  /home/buckman/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/printf.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/errno.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/limits.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/services.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/quad.h \
  /home/buckman/kaneton/kaneton/include/kaneton.h \
  /home/buckman/kaneton/kaneton/include/core/core.h \
  /home/buckman/kaneton/kaneton/include/core/as.h \
  /home/buckman/kaneton/kaneton/include/core/serial.h \
  /home/buckman/kaneton/kaneton/include/core/error.h \
  /home/buckman/kaneton/kaneton/include/core/kernel.h \
  /home/buckman/kaneton/kaneton/include/core/init.h \
  /home/buckman/kaneton/kaneton/include/core/segment.h \
  /home/buckman/kaneton/kaneton/include/core/region.h \
  /home/buckman/kaneton/kaneton/include/core/cpu.h \
  /home/buckman/kaneton/kaneton/include/core/map.h \
  /home/buckman/kaneton/kaneton/include/core/set.h \
  /home/buckman/kaneton/kaneton/include/core/set-array.h \
  /home/buckman/kaneton/kaneton/include/core/set-bpt.h \
  /home/buckman/kaneton/kaneton/include/sys/bpt.h \
  /home/buckman/kaneton/kaneton/include/core/set-ll.h \
  /home/buckman/kaneton/kaneton/include/core/event.h \
  /home/buckman/kaneton/kaneton/include/core/timer.h \
  /home/buckman/kaneton/kaneton/include/core/thread.h \
  /home/buckman/kaneton/kaneton/include/core/wait.h \
  /home/buckman/kaneton/kaneton/include/core/task.h \
  /home/buckman/kaneton/kaneton/include/core/sched.h \
  /home/buckman/kaneton/kaneton/include/core/message.h \
  /home/buckman/kaneton/kaneton/include/core/capability.h \
  /home/buckman/kaneton/kaneton/include/core/interface.h \
  /home/buckman/kaneton/kaneton/include/core/io.h \
  /home/buckman/kaneton/kaneton/include/sys/sys.h \
  /home/buckman/kaneton/kaneton/include/sys/elf.h
segment.o: segment.c /home/buckman/kaneton/libs/klibc/include/klibc.h \
  /home/buckman/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/types.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/machdep.h \
  /home/buckman/kaneton/libs/libia32/include/libia32.h \
  /home/buckman/kaneton/libs/libia32/include/misc/asm.h \
  /home/buckman/kaneton/libs/libia32/include/misc/isa.h \
  /home/buckman/kaneton/libs/libia32/include/misc/multiboot.h \
  /home/buckman/kaneton/libs/libia32/include/misc/stdarg.h \
  /home/buckman/kaneton/libs/libia32/include/misc/types.h \
  /home/buckman/kaneton/kaneton/include/core/types.h \
  /home/buckman/kaneton/libs/libia32/include/misc/spinlock.h \
  /home/buckman/kaneton/libs/libia32/include/paging/paging.h \
  /home/buckman/kaneton/libs/libia32/include/paging/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/pmode.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/gdt.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/idt.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/interrupt.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/pic.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/ipi.h \
  /home/buckman/kaneton/libs/libia32/include/time/pit.h \
  /home/buckman/kaneton/libs/libia32/include/task/context.h \
  /home/buckman/kaneton/libs/libia32/include/task/tss.h \
  /home/buckman/kaneton/libs/libia32/include/apic/apic.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/core.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/as.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/debug.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/init.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/services/cons.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/region.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/segment.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/stats.h \
  /home/buckman/kaneton/kaneton/include/core/stats.h \
  /home/buckman/kaneton/kaneton/include/core/id.h \
  /home/buckman/kaneton/kaneton/include/core/conf.h \
  /home/buckman/kaneton/kaneton/include/core/debug.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/event.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/timer.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/thread.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/task.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/sched.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/message.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/cpu.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/io.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/services/services.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/sys/sys.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/sys/elf.h \
  /home/buckman/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/printf.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/errno.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/limits.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/services.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/quad.h \
  /home/buckman/kaneton/kaneton/include/kaneton.h \
  /home/buckman/kaneton/kaneton/include/core/core.h \
  /home/buckman/kaneton/kaneton/include/core/as.h \
  /home/buckman/kaneton/kaneton/include/core/serial.h \
  /home/buckman/kaneton/kaneton/include/core/error.h \
  /home/buckman/kaneton/kaneton/include/core/kernel.h \
  /home/buckman/kaneton/kaneton/include/core/init.h \
  /home/buckman/kaneton/kaneton/include/core/segment.h \
  /home/buckman/kaneton/kaneton/include/core/region.h \
  /home/buckman/kaneton/kaneton/include/core/cpu.h \
  /home/buckman/kaneton/kaneton/include/core/map.h \
  /home/buckman/kaneton/kaneton/include/core/set.h \
  /home/buckman/kaneton/kaneton/include/core/set-array.h \
  /home/buckman/kaneton/kaneton/include/core/set-bpt.h \
  /home/buckman/kaneton/kaneton/include/sys/bpt.h \
  /home/buckman/kaneton/kaneton/include/core/set-ll.h \
  /home/buckman/kaneton/kaneton/include/core/event.h \
  /home/buckman/kaneton/kaneton/include/core/timer.h \
  /home/buckman/kaneton/kaneton/include/core/thread.h \
  /home/buckman/kaneton/kaneton/include/core/wait.h \
  /home/buckman/kaneton/kaneton/include/core/task.h \
  /home/buckman/kaneton/kaneton/include/core/sched.h \
  /home/buckman/kaneton/kaneton/include/core/message.h \
  /home/buckman/kaneton/kaneton/include/core/capability.h \
  /home/buckman/kaneton/kaneton/include/core/interface.h \
  /home/buckman/kaneton/kaneton/include/core/io.h \
  /home/buckman/kaneton/kaneton/include/sys/sys.h \
  /home/buckman/kaneton/kaneton/include/sys/elf.h
event.o: event.c /home/buckman/kaneton/libs/klibc/include/klibc.h \
  /home/buckman/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/types.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/machdep.h \
  /home/buckman/kaneton/libs/libia32/include/libia32.h \
  /home/buckman/kaneton/libs/libia32/include/misc/asm.h \
  /home/buckman/kaneton/libs/libia32/include/misc/isa.h \
  /home/buckman/kaneton/libs/libia32/include/misc/multiboot.h \
  /home/buckman/kaneton/libs/libia32/include/misc/stdarg.h \
  /home/buckman/kaneton/libs/libia32/include/misc/types.h \
  /home/buckman/kaneton/kaneton/include/core/types.h \
  /home/buckman/kaneton/libs/libia32/include/misc/spinlock.h \
  /home/buckman/kaneton/libs/libia32/include/paging/paging.h \
  /home/buckman/kaneton/libs/libia32/include/paging/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/pmode.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/gdt.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/idt.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/interrupt.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/pic.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/ipi.h \
  /home/buckman/kaneton/libs/libia32/include/time/pit.h \
  /home/buckman/kaneton/libs/libia32/include/task/context.h \
  /home/buckman/kaneton/libs/libia32/include/task/tss.h \
  /home/buckman/kaneton/libs/libia32/include/apic/apic.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/core.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/as.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/debug.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/init.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/services/cons.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/region.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/segment.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/stats.h \
  /home/buckman/kaneton/kaneton/include/core/stats.h \
  /home/buckman/kaneton/kaneton/include/core/id.h \
  /home/buckman/kaneton/kaneton/include/core/conf.h \
  /home/buckman/kaneton/kaneton/include/core/debug.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/event.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/timer.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/thread.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/task.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/sched.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/message.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/cpu.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/io.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/services/services.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/sys/sys.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/sys/elf.h \
  /home/buckman/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/printf.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/errno.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/limits.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/services.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/quad.h \
  /home/buckman/kaneton/kaneton/include/kaneton.h \
  /home/buckman/kaneton/kaneton/include/core/core.h \
  /home/buckman/kaneton/kaneton/include/core/as.h \
  /home/buckman/kaneton/kaneton/include/core/serial.h \
  /home/buckman/kaneton/kaneton/include/core/error.h \
  /home/buckman/kaneton/kaneton/include/core/kernel.h \
  /home/buckman/kaneton/kaneton/include/core/init.h \
  /home/buckman/kaneton/kaneton/include/core/segment.h \
  /home/buckman/kaneton/kaneton/include/core/region.h \
  /home/buckman/kaneton/kaneton/include/core/cpu.h \
  /home/buckman/kaneton/kaneton/include/core/map.h \
  /home/buckman/kaneton/kaneton/include/core/set.h \
  /home/buckman/kaneton/kaneton/include/core/set-array.h \
  /home/buckman/kaneton/kaneton/include/core/set-bpt.h \
  /home/buckman/kaneton/kaneton/include/sys/bpt.h \
  /home/buckman/kaneton/kaneton/include/core/set-ll.h \
  /home/buckman/kaneton/kaneton/include/core/event.h \
  /home/buckman/kaneton/kaneton/include/core/timer.h \
  /home/buckman/kaneton/kaneton/include/core/thread.h \
  /home/buckman/kaneton/kaneton/include/core/wait.h \
  /home/buckman/kaneton/kaneton/include/core/task.h \
  /home/buckman/kaneton/kaneton/include/core/sched.h \
  /home/buckman/kaneton/kaneton/include/core/message.h \
  /home/buckman/kaneton/kaneton/include/core/capability.h \
  /home/buckman/kaneton/kaneton/include/core/interface.h \
  /home/buckman/kaneton/kaneton/include/core/io.h \
  /home/buckman/kaneton/kaneton/include/sys/sys.h \
  /home/buckman/kaneton/kaneton/include/sys/elf.h
timer.o: timer.c /home/buckman/kaneton/libs/klibc/include/klibc.h \
  /home/buckman/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/types.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/machdep.h \
  /home/buckman/kaneton/libs/libia32/include/libia32.h \
  /home/buckman/kaneton/libs/libia32/include/misc/asm.h \
  /home/buckman/kaneton/libs/libia32/include/misc/isa.h \
  /home/buckman/kaneton/libs/libia32/include/misc/multiboot.h \
  /home/buckman/kaneton/libs/libia32/include/misc/stdarg.h \
  /home/buckman/kaneton/libs/libia32/include/misc/types.h \
  /home/buckman/kaneton/kaneton/include/core/types.h \
  /home/buckman/kaneton/libs/libia32/include/misc/spinlock.h \
  /home/buckman/kaneton/libs/libia32/include/paging/paging.h \
  /home/buckman/kaneton/libs/libia32/include/paging/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/pmode.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/gdt.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/idt.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/interrupt.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/pic.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/ipi.h \
  /home/buckman/kaneton/libs/libia32/include/time/pit.h \
  /home/buckman/kaneton/libs/libia32/include/task/context.h \
  /home/buckman/kaneton/libs/libia32/include/task/tss.h \
  /home/buckman/kaneton/libs/libia32/include/apic/apic.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/core.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/as.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/debug.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/init.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/services/cons.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/region.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/segment.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/stats.h \
  /home/buckman/kaneton/kaneton/include/core/stats.h \
  /home/buckman/kaneton/kaneton/include/core/id.h \
  /home/buckman/kaneton/kaneton/include/core/conf.h \
  /home/buckman/kaneton/kaneton/include/core/debug.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/event.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/timer.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/thread.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/task.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/sched.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/message.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/cpu.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/io.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/services/services.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/sys/sys.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/sys/elf.h \
  /home/buckman/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/printf.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/errno.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/limits.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/services.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/quad.h \
  /home/buckman/kaneton/kaneton/include/kaneton.h \
  /home/buckman/kaneton/kaneton/include/core/core.h \
  /home/buckman/kaneton/kaneton/include/core/as.h \
  /home/buckman/kaneton/kaneton/include/core/serial.h \
  /home/buckman/kaneton/kaneton/include/core/error.h \
  /home/buckman/kaneton/kaneton/include/core/kernel.h \
  /home/buckman/kaneton/kaneton/include/core/init.h \
  /home/buckman/kaneton/kaneton/include/core/segment.h \
  /home/buckman/kaneton/kaneton/include/core/region.h \
  /home/buckman/kaneton/kaneton/include/core/cpu.h \
  /home/buckman/kaneton/kaneton/include/core/map.h \
  /home/buckman/kaneton/kaneton/include/core/set.h \
  /home/buckman/kaneton/kaneton/include/core/set-array.h \
  /home/buckman/kaneton/kaneton/include/core/set-bpt.h \
  /home/buckman/kaneton/kaneton/include/sys/bpt.h \
  /home/buckman/kaneton/kaneton/include/core/set-ll.h \
  /home/buckman/kaneton/kaneton/include/core/event.h \
  /home/buckman/kaneton/kaneton/include/core/timer.h \
  /home/buckman/kaneton/kaneton/include/core/thread.h \
  /home/buckman/kaneton/kaneton/include/core/wait.h \
  /home/buckman/kaneton/kaneton/include/core/task.h \
  /home/buckman/kaneton/kaneton/include/core/sched.h \
  /home/buckman/kaneton/kaneton/include/core/message.h \
  /home/buckman/kaneton/kaneton/include/core/capability.h \
  /home/buckman/kaneton/kaneton/include/core/interface.h \
  /home/buckman/kaneton/kaneton/include/core/io.h \
  /home/buckman/kaneton/kaneton/include/sys/sys.h \
  /home/buckman/kaneton/kaneton/include/sys/elf.h
thread.o: thread.c /home/buckman/kaneton/libs/klibc/include/klibc.h \
  /home/buckman/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/types.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/machdep.h \
  /home/buckman/kaneton/libs/libia32/include/libia32.h \
  /home/buckman/kaneton/libs/libia32/include/misc/asm.h \
  /home/buckman/kaneton/libs/libia32/include/misc/isa.h \
  /home/buckman/kaneton/libs/libia32/include/misc/multiboot.h \
  /home/buckman/kaneton/libs/libia32/include/misc/stdarg.h \
  /home/buckman/kaneton/libs/libia32/include/misc/types.h \
  /home/buckman/kaneton/kaneton/include/core/types.h \
  /home/buckman/kaneton/libs/libia32/include/misc/spinlock.h \
  /home/buckman/kaneton/libs/libia32/include/paging/paging.h \
  /home/buckman/kaneton/libs/libia32/include/paging/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/pmode.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/gdt.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/idt.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/interrupt.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/pic.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/ipi.h \
  /home/buckman/kaneton/libs/libia32/include/time/pit.h \
  /home/buckman/kaneton/libs/libia32/include/task/context.h \
  /home/buckman/kaneton/libs/libia32/include/task/tss.h \
  /home/buckman/kaneton/libs/libia32/include/apic/apic.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/core.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/as.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/debug.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/init.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/services/cons.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/region.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/segment.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/stats.h \
  /home/buckman/kaneton/kaneton/include/core/stats.h \
  /home/buckman/kaneton/kaneton/include/core/id.h \
  /home/buckman/kaneton/kaneton/include/core/conf.h \
  /home/buckman/kaneton/kaneton/include/core/debug.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/event.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/timer.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/thread.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/task.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/sched.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/message.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/cpu.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/io.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/services/services.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/sys/sys.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/sys/elf.h \
  /home/buckman/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/printf.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/errno.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/limits.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/services.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/quad.h \
  /home/buckman/kaneton/kaneton/include/kaneton.h \
  /home/buckman/kaneton/kaneton/include/core/core.h \
  /home/buckman/kaneton/kaneton/include/core/as.h \
  /home/buckman/kaneton/kaneton/include/core/serial.h \
  /home/buckman/kaneton/kaneton/include/core/error.h \
  /home/buckman/kaneton/kaneton/include/core/kernel.h \
  /home/buckman/kaneton/kaneton/include/core/init.h \
  /home/buckman/kaneton/kaneton/include/core/segment.h \
  /home/buckman/kaneton/kaneton/include/core/region.h \
  /home/buckman/kaneton/kaneton/include/core/cpu.h \
  /home/buckman/kaneton/kaneton/include/core/map.h \
  /home/buckman/kaneton/kaneton/include/core/set.h \
  /home/buckman/kaneton/kaneton/include/core/set-array.h \
  /home/buckman/kaneton/kaneton/include/core/set-bpt.h \
  /home/buckman/kaneton/kaneton/include/sys/bpt.h \
  /home/buckman/kaneton/kaneton/include/core/set-ll.h \
  /home/buckman/kaneton/kaneton/include/core/event.h \
  /home/buckman/kaneton/kaneton/include/core/timer.h \
  /home/buckman/kaneton/kaneton/include/core/thread.h \
  /home/buckman/kaneton/kaneton/include/core/wait.h \
  /home/buckman/kaneton/kaneton/include/core/task.h \
  /home/buckman/kaneton/kaneton/include/core/sched.h \
  /home/buckman/kaneton/kaneton/include/core/message.h \
  /home/buckman/kaneton/kaneton/include/core/capability.h \
  /home/buckman/kaneton/kaneton/include/core/interface.h \
  /home/buckman/kaneton/kaneton/include/core/io.h \
  /home/buckman/kaneton/kaneton/include/sys/sys.h \
  /home/buckman/kaneton/kaneton/include/sys/elf.h
task.o: task.c /home/buckman/kaneton/libs/klibc/include/klibc.h \
  /home/buckman/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/types.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/machdep.h \
  /home/buckman/kaneton/libs/libia32/include/libia32.h \
  /home/buckman/kaneton/libs/libia32/include/misc/asm.h \
  /home/buckman/kaneton/libs/libia32/include/misc/isa.h \
  /home/buckman/kaneton/libs/libia32/include/misc/multiboot.h \
  /home/buckman/kaneton/libs/libia32/include/misc/stdarg.h \
  /home/buckman/kaneton/libs/libia32/include/misc/types.h \
  /home/buckman/kaneton/kaneton/include/core/types.h \
  /home/buckman/kaneton/libs/libia32/include/misc/spinlock.h \
  /home/buckman/kaneton/libs/libia32/include/paging/paging.h \
  /home/buckman/kaneton/libs/libia32/include/paging/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/pmode.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/gdt.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/idt.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/interrupt.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/pic.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/ipi.h \
  /home/buckman/kaneton/libs/libia32/include/time/pit.h \
  /home/buckman/kaneton/libs/libia32/include/task/context.h \
  /home/buckman/kaneton/libs/libia32/include/task/tss.h \
  /home/buckman/kaneton/libs/libia32/include/apic/apic.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/core.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/as.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/debug.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/init.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/services/cons.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/region.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/segment.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/stats.h \
  /home/buckman/kaneton/kaneton/include/core/stats.h \
  /home/buckman/kaneton/kaneton/include/core/id.h \
  /home/buckman/kaneton/kaneton/include/core/conf.h \
  /home/buckman/kaneton/kaneton/include/core/debug.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/event.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/timer.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/thread.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/task.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/sched.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/message.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/cpu.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/io.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/services/services.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/sys/sys.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/sys/elf.h \
  /home/buckman/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/printf.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/errno.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/limits.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/services.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/quad.h \
  /home/buckman/kaneton/kaneton/include/kaneton.h \
  /home/buckman/kaneton/kaneton/include/core/core.h \
  /home/buckman/kaneton/kaneton/include/core/as.h \
  /home/buckman/kaneton/kaneton/include/core/serial.h \
  /home/buckman/kaneton/kaneton/include/core/error.h \
  /home/buckman/kaneton/kaneton/include/core/kernel.h \
  /home/buckman/kaneton/kaneton/include/core/init.h \
  /home/buckman/kaneton/kaneton/include/core/segment.h \
  /home/buckman/kaneton/kaneton/include/core/region.h \
  /home/buckman/kaneton/kaneton/include/core/cpu.h \
  /home/buckman/kaneton/kaneton/include/core/map.h \
  /home/buckman/kaneton/kaneton/include/core/set.h \
  /home/buckman/kaneton/kaneton/include/core/set-array.h \
  /home/buckman/kaneton/kaneton/include/core/set-bpt.h \
  /home/buckman/kaneton/kaneton/include/sys/bpt.h \
  /home/buckman/kaneton/kaneton/include/core/set-ll.h \
  /home/buckman/kaneton/kaneton/include/core/event.h \
  /home/buckman/kaneton/kaneton/include/core/timer.h \
  /home/buckman/kaneton/kaneton/include/core/thread.h \
  /home/buckman/kaneton/kaneton/include/core/wait.h \
  /home/buckman/kaneton/kaneton/include/core/task.h \
  /home/buckman/kaneton/kaneton/include/core/sched.h \
  /home/buckman/kaneton/kaneton/include/core/message.h \
  /home/buckman/kaneton/kaneton/include/core/capability.h \
  /home/buckman/kaneton/kaneton/include/core/interface.h \
  /home/buckman/kaneton/kaneton/include/core/io.h \
  /home/buckman/kaneton/kaneton/include/sys/sys.h \
  /home/buckman/kaneton/kaneton/include/sys/elf.h
sched.o: sched.c /home/buckman/kaneton/libs/klibc/include/klibc.h \
  /home/buckman/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/types.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/machdep.h \
  /home/buckman/kaneton/libs/libia32/include/libia32.h \
  /home/buckman/kaneton/libs/libia32/include/misc/asm.h \
  /home/buckman/kaneton/libs/libia32/include/misc/isa.h \
  /home/buckman/kaneton/libs/libia32/include/misc/multiboot.h \
  /home/buckman/kaneton/libs/libia32/include/misc/stdarg.h \
  /home/buckman/kaneton/libs/libia32/include/misc/types.h \
  /home/buckman/kaneton/kaneton/include/core/types.h \
  /home/buckman/kaneton/libs/libia32/include/misc/spinlock.h \
  /home/buckman/kaneton/libs/libia32/include/paging/paging.h \
  /home/buckman/kaneton/libs/libia32/include/paging/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/pmode.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/gdt.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/idt.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/interrupt.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/pic.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/ipi.h \
  /home/buckman/kaneton/libs/libia32/include/time/pit.h \
  /home/buckman/kaneton/libs/libia32/include/task/context.h \
  /home/buckman/kaneton/libs/libia32/include/task/tss.h \
  /home/buckman/kaneton/libs/libia32/include/apic/apic.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/core.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/as.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/debug.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/init.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/services/cons.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/region.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/segment.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/stats.h \
  /home/buckman/kaneton/kaneton/include/core/stats.h \
  /home/buckman/kaneton/kaneton/include/core/id.h \
  /home/buckman/kaneton/kaneton/include/core/conf.h \
  /home/buckman/kaneton/kaneton/include/core/debug.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/event.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/timer.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/thread.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/task.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/sched.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/message.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/cpu.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/io.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/services/services.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/sys/sys.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/sys/elf.h \
  /home/buckman/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/printf.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/errno.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/limits.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/services.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/quad.h \
  /home/buckman/kaneton/kaneton/include/kaneton.h \
  /home/buckman/kaneton/kaneton/include/core/core.h \
  /home/buckman/kaneton/kaneton/include/core/as.h \
  /home/buckman/kaneton/kaneton/include/core/serial.h \
  /home/buckman/kaneton/kaneton/include/core/error.h \
  /home/buckman/kaneton/kaneton/include/core/kernel.h \
  /home/buckman/kaneton/kaneton/include/core/init.h \
  /home/buckman/kaneton/kaneton/include/core/segment.h \
  /home/buckman/kaneton/kaneton/include/core/region.h \
  /home/buckman/kaneton/kaneton/include/core/cpu.h \
  /home/buckman/kaneton/kaneton/include/core/map.h \
  /home/buckman/kaneton/kaneton/include/core/set.h \
  /home/buckman/kaneton/kaneton/include/core/set-array.h \
  /home/buckman/kaneton/kaneton/include/core/set-bpt.h \
  /home/buckman/kaneton/kaneton/include/sys/bpt.h \
  /home/buckman/kaneton/kaneton/include/core/set-ll.h \
  /home/buckman/kaneton/kaneton/include/core/event.h \
  /home/buckman/kaneton/kaneton/include/core/timer.h \
  /home/buckman/kaneton/kaneton/include/core/thread.h \
  /home/buckman/kaneton/kaneton/include/core/wait.h \
  /home/buckman/kaneton/kaneton/include/core/task.h \
  /home/buckman/kaneton/kaneton/include/core/sched.h \
  /home/buckman/kaneton/kaneton/include/core/message.h \
  /home/buckman/kaneton/kaneton/include/core/capability.h \
  /home/buckman/kaneton/kaneton/include/core/interface.h \
  /home/buckman/kaneton/kaneton/include/core/io.h \
  /home/buckman/kaneton/kaneton/include/sys/sys.h \
  /home/buckman/kaneton/kaneton/include/sys/elf.h
message.o: message.c /home/buckman/kaneton/libs/klibc/include/klibc.h \
  /home/buckman/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/types.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/machdep.h \
  /home/buckman/kaneton/libs/libia32/include/libia32.h \
  /home/buckman/kaneton/libs/libia32/include/misc/asm.h \
  /home/buckman/kaneton/libs/libia32/include/misc/isa.h \
  /home/buckman/kaneton/libs/libia32/include/misc/multiboot.h \
  /home/buckman/kaneton/libs/libia32/include/misc/stdarg.h \
  /home/buckman/kaneton/libs/libia32/include/misc/types.h \
  /home/buckman/kaneton/kaneton/include/core/types.h \
  /home/buckman/kaneton/libs/libia32/include/misc/spinlock.h \
  /home/buckman/kaneton/libs/libia32/include/paging/paging.h \
  /home/buckman/kaneton/libs/libia32/include/paging/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/pmode.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/gdt.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/idt.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/interrupt.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/pic.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/ipi.h \
  /home/buckman/kaneton/libs/libia32/include/time/pit.h \
  /home/buckman/kaneton/libs/libia32/include/task/context.h \
  /home/buckman/kaneton/libs/libia32/include/task/tss.h \
  /home/buckman/kaneton/libs/libia32/include/apic/apic.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/core.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/as.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/debug.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/init.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/services/cons.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/region.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/segment.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/stats.h \
  /home/buckman/kaneton/kaneton/include/core/stats.h \
  /home/buckman/kaneton/kaneton/include/core/id.h \
  /home/buckman/kaneton/kaneton/include/core/conf.h \
  /home/buckman/kaneton/kaneton/include/core/debug.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/event.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/timer.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/thread.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/task.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/sched.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/message.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/cpu.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/io.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/services/services.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/sys/sys.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/sys/elf.h \
  /home/buckman/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/printf.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/errno.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/limits.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/services.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/quad.h \
  /home/buckman/kaneton/kaneton/include/kaneton.h \
  /home/buckman/kaneton/kaneton/include/core/core.h \
  /home/buckman/kaneton/kaneton/include/core/as.h \
  /home/buckman/kaneton/kaneton/include/core/serial.h \
  /home/buckman/kaneton/kaneton/include/core/error.h \
  /home/buckman/kaneton/kaneton/include/core/kernel.h \
  /home/buckman/kaneton/kaneton/include/core/init.h \
  /home/buckman/kaneton/kaneton/include/core/segment.h \
  /home/buckman/kaneton/kaneton/include/core/region.h \
  /home/buckman/kaneton/kaneton/include/core/cpu.h \
  /home/buckman/kaneton/kaneton/include/core/map.h \
  /home/buckman/kaneton/kaneton/include/core/set.h \
  /home/buckman/kaneton/kaneton/include/core/set-array.h \
  /home/buckman/kaneton/kaneton/include/core/set-bpt.h \
  /home/buckman/kaneton/kaneton/include/sys/bpt.h \
  /home/buckman/kaneton/kaneton/include/core/set-ll.h \
  /home/buckman/kaneton/kaneton/include/core/event.h \
  /home/buckman/kaneton/kaneton/include/core/timer.h \
  /home/buckman/kaneton/kaneton/include/core/thread.h \
  /home/buckman/kaneton/kaneton/include/core/wait.h \
  /home/buckman/kaneton/kaneton/include/core/task.h \
  /home/buckman/kaneton/kaneton/include/core/sched.h \
  /home/buckman/kaneton/kaneton/include/core/message.h \
  /home/buckman/kaneton/kaneton/include/core/capability.h \
  /home/buckman/kaneton/kaneton/include/core/interface.h \
  /home/buckman/kaneton/kaneton/include/core/io.h \
  /home/buckman/kaneton/kaneton/include/sys/sys.h \
  /home/buckman/kaneton/kaneton/include/sys/elf.h
cpu.o: cpu.c /home/buckman/kaneton/libs/klibc/include/klibc.h \
  /home/buckman/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/types.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/machdep.h \
  /home/buckman/kaneton/libs/libia32/include/libia32.h \
  /home/buckman/kaneton/libs/libia32/include/misc/asm.h \
  /home/buckman/kaneton/libs/libia32/include/misc/isa.h \
  /home/buckman/kaneton/libs/libia32/include/misc/multiboot.h \
  /home/buckman/kaneton/libs/libia32/include/misc/stdarg.h \
  /home/buckman/kaneton/libs/libia32/include/misc/types.h \
  /home/buckman/kaneton/kaneton/include/core/types.h \
  /home/buckman/kaneton/libs/libia32/include/misc/spinlock.h \
  /home/buckman/kaneton/libs/libia32/include/paging/paging.h \
  /home/buckman/kaneton/libs/libia32/include/paging/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/pmode.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/gdt.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/idt.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/interrupt.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/pic.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/ipi.h \
  /home/buckman/kaneton/libs/libia32/include/time/pit.h \
  /home/buckman/kaneton/libs/libia32/include/task/context.h \
  /home/buckman/kaneton/libs/libia32/include/task/tss.h \
  /home/buckman/kaneton/libs/libia32/include/apic/apic.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/core.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/as.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/debug.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/init.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/services/cons.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/region.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/segment.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/stats.h \
  /home/buckman/kaneton/kaneton/include/core/stats.h \
  /home/buckman/kaneton/kaneton/include/core/id.h \
  /home/buckman/kaneton/kaneton/include/core/conf.h \
  /home/buckman/kaneton/kaneton/include/core/debug.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/event.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/timer.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/thread.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/task.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/sched.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/message.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/cpu.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/io.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/services/services.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/sys/sys.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/sys/elf.h \
  /home/buckman/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/printf.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/errno.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/limits.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/services.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/quad.h \
  /home/buckman/kaneton/kaneton/include/kaneton.h \
  /home/buckman/kaneton/kaneton/include/core/core.h \
  /home/buckman/kaneton/kaneton/include/core/as.h \
  /home/buckman/kaneton/kaneton/include/core/serial.h \
  /home/buckman/kaneton/kaneton/include/core/error.h \
  /home/buckman/kaneton/kaneton/include/core/kernel.h \
  /home/buckman/kaneton/kaneton/include/core/init.h \
  /home/buckman/kaneton/kaneton/include/core/segment.h \
  /home/buckman/kaneton/kaneton/include/core/region.h \
  /home/buckman/kaneton/kaneton/include/core/cpu.h \
  /home/buckman/kaneton/kaneton/include/core/map.h \
  /home/buckman/kaneton/kaneton/include/core/set.h \
  /home/buckman/kaneton/kaneton/include/core/set-array.h \
  /home/buckman/kaneton/kaneton/include/core/set-bpt.h \
  /home/buckman/kaneton/kaneton/include/sys/bpt.h \
  /home/buckman/kaneton/kaneton/include/core/set-ll.h \
  /home/buckman/kaneton/kaneton/include/core/event.h \
  /home/buckman/kaneton/kaneton/include/core/timer.h \
  /home/buckman/kaneton/kaneton/include/core/thread.h \
  /home/buckman/kaneton/kaneton/include/core/wait.h \
  /home/buckman/kaneton/kaneton/include/core/task.h \
  /home/buckman/kaneton/kaneton/include/core/sched.h \
  /home/buckman/kaneton/kaneton/include/core/message.h \
  /home/buckman/kaneton/kaneton/include/core/capability.h \
  /home/buckman/kaneton/kaneton/include/core/interface.h \
  /home/buckman/kaneton/kaneton/include/core/io.h \
  /home/buckman/kaneton/kaneton/include/sys/sys.h \
  /home/buckman/kaneton/kaneton/include/sys/elf.h
io.o: io.c /home/buckman/kaneton/libs/klibc/include/klibc.h \
  /home/buckman/kaneton/libs/klibc/include/libdata/libdata.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/types.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/machdep.h \
  /home/buckman/kaneton/libs/libia32/include/libia32.h \
  /home/buckman/kaneton/libs/libia32/include/misc/asm.h \
  /home/buckman/kaneton/libs/libia32/include/misc/isa.h \
  /home/buckman/kaneton/libs/libia32/include/misc/multiboot.h \
  /home/buckman/kaneton/libs/libia32/include/misc/stdarg.h \
  /home/buckman/kaneton/libs/libia32/include/misc/types.h \
  /home/buckman/kaneton/kaneton/include/core/types.h \
  /home/buckman/kaneton/libs/libia32/include/misc/spinlock.h \
  /home/buckman/kaneton/libs/libia32/include/paging/paging.h \
  /home/buckman/kaneton/libs/libia32/include/paging/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/pmode.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/gdt.h \
  /home/buckman/kaneton/libs/libia32/include/pmode/idt.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/interrupt.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/../misc/types.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/pic.h \
  /home/buckman/kaneton/libs/libia32/include/interrupt/ipi.h \
  /home/buckman/kaneton/libs/libia32/include/time/pit.h \
  /home/buckman/kaneton/libs/libia32/include/task/context.h \
  /home/buckman/kaneton/libs/libia32/include/task/tss.h \
  /home/buckman/kaneton/libs/libia32/include/apic/apic.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/core.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/as.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/debug.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/init.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/services/cons.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/region.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/segment.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/stats.h \
  /home/buckman/kaneton/kaneton/include/core/stats.h \
  /home/buckman/kaneton/kaneton/include/core/id.h \
  /home/buckman/kaneton/kaneton/include/core/conf.h \
  /home/buckman/kaneton/kaneton/include/core/debug.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/event.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/timer.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/thread.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/task.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/sched.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/message.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/cpu.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/core/io.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/services/services.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/sys/sys.h \
  /home/buckman/kaneton/kaneton/include/arch/machdep/sys/elf.h \
  /home/buckman/kaneton/libs/klibc/include/libdata/alloc.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/libstring.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/ctype.h \
  /home/buckman/kaneton/libs/klibc/include/libstring/printf.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/errno.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/limits.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/services.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/buckman/kaneton/libs/klibc/include/libsys/quad.h \
  /home/buckman/kaneton/kaneton/include/kaneton.h \
  /home/buckman/kaneton/kaneton/include/core/core.h \
  /home/buckman/kaneton/kaneton/include/core/as.h \
  /home/buckman/kaneton/kaneton/include/core/serial.h \
  /home/buckman/kaneton/kaneton/include/core/error.h \
  /home/buckman/kaneton/kaneton/include/core/kernel.h \
  /home/buckman/kaneton/kaneton/include/core/init.h \
  /home/buckman/kaneton/kaneton/include/core/segment.h \
  /home/buckman/kaneton/kaneton/include/core/region.h \
  /home/buckman/kaneton/kaneton/include/core/cpu.h \
  /home/buckman/kaneton/kaneton/include/core/map.h \
  /home/buckman/kaneton/kaneton/include/core/set.h \
  /home/buckman/kaneton/kaneton/include/core/set-array.h \
  /home/buckman/kaneton/kaneton/include/core/set-bpt.h \
  /home/buckman/kaneton/kaneton/include/sys/bpt.h \
  /home/buckman/kaneton/kaneton/include/core/set-ll.h \
  /home/buckman/kaneton/kaneton/include/core/event.h \
  /home/buckman/kaneton/kaneton/include/core/timer.h \
  /home/buckman/kaneton/kaneton/include/core/thread.h \
  /home/buckman/kaneton/kaneton/include/core/wait.h \
  /home/buckman/kaneton/kaneton/include/core/task.h \
  /home/buckman/kaneton/kaneton/include/core/sched.h \
  /home/buckman/kaneton/kaneton/include/core/message.h \
  /home/buckman/kaneton/kaneton/include/core/capability.h \
  /home/buckman/kaneton/kaneton/include/core/interface.h \
  /home/buckman/kaneton/kaneton/include/core/io.h \
  /home/buckman/kaneton/kaneton/include/sys/sys.h \
  /home/buckman/kaneton/kaneton/include/sys/elf.h
