_ctype.o: _ctype.c /home/mycure/kaneton/libs/klibc/include/klibc.h \
  /home/mycure/kaneton/libs/klibc/include/libc/libc.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/machdep.h \
  /home/mycure/kaneton/core/include/arch/machdep/asm.h \
  /home/mycure/kaneton/core/include/arch/machdep/stdarg.h \
  /home/mycure/kaneton/core/include/arch/machdep/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/multiboot.h \
  /home/mycure/kaneton/core/include/arch/machdep/elf.h \
  /home/mycure/kaneton/core/include/arch/machdep/kaneton.h \
  /home/mycure/kaneton/core/include/arch/machdep/init.h \
  /home/mycure/kaneton/core/include/arch/machdep/cons.h \
  /home/mycure/kaneton/core/include/arch/machdep/pmode.h \
  /home/mycure/kaneton/core/include/arch/machdep/paging.h \
  /home/mycure/kaneton/core/include/arch/machdep/bootloader.h \
  /home/mycure/kaneton/libs/klibc/include/libc/ctype.h \
  /home/mycure/kaneton/libs/klibc/include/libc/printf.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/errno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/limits.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/services.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/quad.h
bcmp.o: bcmp.c /home/mycure/kaneton/libs/klibc/include/klibc.h \
  /home/mycure/kaneton/libs/klibc/include/libc/libc.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/machdep.h \
  /home/mycure/kaneton/core/include/arch/machdep/asm.h \
  /home/mycure/kaneton/core/include/arch/machdep/stdarg.h \
  /home/mycure/kaneton/core/include/arch/machdep/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/multiboot.h \
  /home/mycure/kaneton/core/include/arch/machdep/elf.h \
  /home/mycure/kaneton/core/include/arch/machdep/kaneton.h \
  /home/mycure/kaneton/core/include/arch/machdep/init.h \
  /home/mycure/kaneton/core/include/arch/machdep/cons.h \
  /home/mycure/kaneton/core/include/arch/machdep/pmode.h \
  /home/mycure/kaneton/core/include/arch/machdep/paging.h \
  /home/mycure/kaneton/core/include/arch/machdep/bootloader.h \
  /home/mycure/kaneton/libs/klibc/include/libc/ctype.h \
  /home/mycure/kaneton/libs/klibc/include/libc/printf.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/errno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/limits.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/services.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/quad.h
bcopy.o: bcopy.c /home/mycure/kaneton/libs/klibc/include/klibc.h \
  /home/mycure/kaneton/libs/klibc/include/libc/libc.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/machdep.h \
  /home/mycure/kaneton/core/include/arch/machdep/asm.h \
  /home/mycure/kaneton/core/include/arch/machdep/stdarg.h \
  /home/mycure/kaneton/core/include/arch/machdep/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/multiboot.h \
  /home/mycure/kaneton/core/include/arch/machdep/elf.h \
  /home/mycure/kaneton/core/include/arch/machdep/kaneton.h \
  /home/mycure/kaneton/core/include/arch/machdep/init.h \
  /home/mycure/kaneton/core/include/arch/machdep/cons.h \
  /home/mycure/kaneton/core/include/arch/machdep/pmode.h \
  /home/mycure/kaneton/core/include/arch/machdep/paging.h \
  /home/mycure/kaneton/core/include/arch/machdep/bootloader.h \
  /home/mycure/kaneton/libs/klibc/include/libc/ctype.h \
  /home/mycure/kaneton/libs/klibc/include/libc/printf.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/errno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/limits.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/services.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/quad.h
bzero.o: bzero.c /home/mycure/kaneton/libs/klibc/include/klibc.h \
  /home/mycure/kaneton/libs/klibc/include/libc/libc.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/machdep.h \
  /home/mycure/kaneton/core/include/arch/machdep/asm.h \
  /home/mycure/kaneton/core/include/arch/machdep/stdarg.h \
  /home/mycure/kaneton/core/include/arch/machdep/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/multiboot.h \
  /home/mycure/kaneton/core/include/arch/machdep/elf.h \
  /home/mycure/kaneton/core/include/arch/machdep/kaneton.h \
  /home/mycure/kaneton/core/include/arch/machdep/init.h \
  /home/mycure/kaneton/core/include/arch/machdep/cons.h \
  /home/mycure/kaneton/core/include/arch/machdep/pmode.h \
  /home/mycure/kaneton/core/include/arch/machdep/paging.h \
  /home/mycure/kaneton/core/include/arch/machdep/bootloader.h \
  /home/mycure/kaneton/libs/klibc/include/libc/ctype.h \
  /home/mycure/kaneton/libs/klibc/include/libc/printf.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/errno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/limits.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/services.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/quad.h
dump.o: dump.c /home/mycure/kaneton/libs/klibc/include/klibc.h \
  /home/mycure/kaneton/libs/klibc/include/libc/libc.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/machdep.h \
  /home/mycure/kaneton/core/include/arch/machdep/asm.h \
  /home/mycure/kaneton/core/include/arch/machdep/stdarg.h \
  /home/mycure/kaneton/core/include/arch/machdep/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/multiboot.h \
  /home/mycure/kaneton/core/include/arch/machdep/elf.h \
  /home/mycure/kaneton/core/include/arch/machdep/kaneton.h \
  /home/mycure/kaneton/core/include/arch/machdep/init.h \
  /home/mycure/kaneton/core/include/arch/machdep/cons.h \
  /home/mycure/kaneton/core/include/arch/machdep/pmode.h \
  /home/mycure/kaneton/core/include/arch/machdep/paging.h \
  /home/mycure/kaneton/core/include/arch/machdep/bootloader.h \
  /home/mycure/kaneton/libs/klibc/include/libc/ctype.h \
  /home/mycure/kaneton/libs/klibc/include/libc/printf.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/errno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/limits.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/services.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/quad.h
index.o: index.c /home/mycure/kaneton/libs/klibc/include/klibc.h \
  /home/mycure/kaneton/libs/klibc/include/libc/libc.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/machdep.h \
  /home/mycure/kaneton/core/include/arch/machdep/asm.h \
  /home/mycure/kaneton/core/include/arch/machdep/stdarg.h \
  /home/mycure/kaneton/core/include/arch/machdep/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/multiboot.h \
  /home/mycure/kaneton/core/include/arch/machdep/elf.h \
  /home/mycure/kaneton/core/include/arch/machdep/kaneton.h \
  /home/mycure/kaneton/core/include/arch/machdep/init.h \
  /home/mycure/kaneton/core/include/arch/machdep/cons.h \
  /home/mycure/kaneton/core/include/arch/machdep/pmode.h \
  /home/mycure/kaneton/core/include/arch/machdep/paging.h \
  /home/mycure/kaneton/core/include/arch/machdep/bootloader.h \
  /home/mycure/kaneton/libs/klibc/include/libc/ctype.h \
  /home/mycure/kaneton/libs/klibc/include/libc/printf.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/errno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/limits.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/services.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/quad.h
memcmp.o: memcmp.c /home/mycure/kaneton/libs/klibc/include/klibc.h \
  /home/mycure/kaneton/libs/klibc/include/libc/libc.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/machdep.h \
  /home/mycure/kaneton/core/include/arch/machdep/asm.h \
  /home/mycure/kaneton/core/include/arch/machdep/stdarg.h \
  /home/mycure/kaneton/core/include/arch/machdep/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/multiboot.h \
  /home/mycure/kaneton/core/include/arch/machdep/elf.h \
  /home/mycure/kaneton/core/include/arch/machdep/kaneton.h \
  /home/mycure/kaneton/core/include/arch/machdep/init.h \
  /home/mycure/kaneton/core/include/arch/machdep/cons.h \
  /home/mycure/kaneton/core/include/arch/machdep/pmode.h \
  /home/mycure/kaneton/core/include/arch/machdep/paging.h \
  /home/mycure/kaneton/core/include/arch/machdep/bootloader.h \
  /home/mycure/kaneton/libs/klibc/include/libc/ctype.h \
  /home/mycure/kaneton/libs/klibc/include/libc/printf.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/errno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/limits.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/services.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/quad.h
memcpy.o: memcpy.c /home/mycure/kaneton/libs/klibc/include/klibc.h \
  /home/mycure/kaneton/libs/klibc/include/libc/libc.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/machdep.h \
  /home/mycure/kaneton/core/include/arch/machdep/asm.h \
  /home/mycure/kaneton/core/include/arch/machdep/stdarg.h \
  /home/mycure/kaneton/core/include/arch/machdep/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/multiboot.h \
  /home/mycure/kaneton/core/include/arch/machdep/elf.h \
  /home/mycure/kaneton/core/include/arch/machdep/kaneton.h \
  /home/mycure/kaneton/core/include/arch/machdep/init.h \
  /home/mycure/kaneton/core/include/arch/machdep/cons.h \
  /home/mycure/kaneton/core/include/arch/machdep/pmode.h \
  /home/mycure/kaneton/core/include/arch/machdep/paging.h \
  /home/mycure/kaneton/core/include/arch/machdep/bootloader.h \
  /home/mycure/kaneton/libs/klibc/include/libc/ctype.h \
  /home/mycure/kaneton/libs/klibc/include/libc/printf.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/errno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/limits.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/services.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/quad.h
memset.o: memset.c /home/mycure/kaneton/libs/klibc/include/klibc.h \
  /home/mycure/kaneton/libs/klibc/include/libc/libc.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/machdep.h \
  /home/mycure/kaneton/core/include/arch/machdep/asm.h \
  /home/mycure/kaneton/core/include/arch/machdep/stdarg.h \
  /home/mycure/kaneton/core/include/arch/machdep/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/multiboot.h \
  /home/mycure/kaneton/core/include/arch/machdep/elf.h \
  /home/mycure/kaneton/core/include/arch/machdep/kaneton.h \
  /home/mycure/kaneton/core/include/arch/machdep/init.h \
  /home/mycure/kaneton/core/include/arch/machdep/cons.h \
  /home/mycure/kaneton/core/include/arch/machdep/pmode.h \
  /home/mycure/kaneton/core/include/arch/machdep/paging.h \
  /home/mycure/kaneton/core/include/arch/machdep/bootloader.h \
  /home/mycure/kaneton/libs/klibc/include/libc/ctype.h \
  /home/mycure/kaneton/libs/klibc/include/libc/printf.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/errno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/limits.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/services.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/quad.h
printf.o: printf.c \
  /home/mycure/kaneton/core/include/arch/machdep/machdep.h \
  /home/mycure/kaneton/core/include/arch/machdep/asm.h \
  /home/mycure/kaneton/core/include/arch/machdep/stdarg.h \
  /home/mycure/kaneton/core/include/arch/machdep/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/multiboot.h \
  /home/mycure/kaneton/core/include/arch/machdep/elf.h \
  /home/mycure/kaneton/core/include/arch/machdep/kaneton.h \
  /home/mycure/kaneton/core/include/arch/machdep/init.h \
  /home/mycure/kaneton/core/include/arch/machdep/cons.h \
  /home/mycure/kaneton/core/include/arch/machdep/pmode.h \
  /home/mycure/kaneton/core/include/arch/machdep/paging.h \
  /home/mycure/kaneton/core/include/arch/machdep/bootloader.h \
  /home/mycure/kaneton/libs/klibc/include/klibc.h \
  /home/mycure/kaneton/libs/klibc/include/libc/libc.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/types.h \
  /home/mycure/kaneton/libs/klibc/include/libc/ctype.h \
  /home/mycure/kaneton/libs/klibc/include/libc/printf.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/errno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/limits.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/services.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/quad.h
rindex.o: rindex.c /home/mycure/kaneton/libs/klibc/include/klibc.h \
  /home/mycure/kaneton/libs/klibc/include/libc/libc.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/machdep.h \
  /home/mycure/kaneton/core/include/arch/machdep/asm.h \
  /home/mycure/kaneton/core/include/arch/machdep/stdarg.h \
  /home/mycure/kaneton/core/include/arch/machdep/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/multiboot.h \
  /home/mycure/kaneton/core/include/arch/machdep/elf.h \
  /home/mycure/kaneton/core/include/arch/machdep/kaneton.h \
  /home/mycure/kaneton/core/include/arch/machdep/init.h \
  /home/mycure/kaneton/core/include/arch/machdep/cons.h \
  /home/mycure/kaneton/core/include/arch/machdep/pmode.h \
  /home/mycure/kaneton/core/include/arch/machdep/paging.h \
  /home/mycure/kaneton/core/include/arch/machdep/bootloader.h \
  /home/mycure/kaneton/libs/klibc/include/libc/ctype.h \
  /home/mycure/kaneton/libs/klibc/include/libc/printf.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/errno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/limits.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/services.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/quad.h
strcat.o: strcat.c /home/mycure/kaneton/libs/klibc/include/klibc.h \
  /home/mycure/kaneton/libs/klibc/include/libc/libc.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/machdep.h \
  /home/mycure/kaneton/core/include/arch/machdep/asm.h \
  /home/mycure/kaneton/core/include/arch/machdep/stdarg.h \
  /home/mycure/kaneton/core/include/arch/machdep/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/multiboot.h \
  /home/mycure/kaneton/core/include/arch/machdep/elf.h \
  /home/mycure/kaneton/core/include/arch/machdep/kaneton.h \
  /home/mycure/kaneton/core/include/arch/machdep/init.h \
  /home/mycure/kaneton/core/include/arch/machdep/cons.h \
  /home/mycure/kaneton/core/include/arch/machdep/pmode.h \
  /home/mycure/kaneton/core/include/arch/machdep/paging.h \
  /home/mycure/kaneton/core/include/arch/machdep/bootloader.h \
  /home/mycure/kaneton/libs/klibc/include/libc/ctype.h \
  /home/mycure/kaneton/libs/klibc/include/libc/printf.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/errno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/limits.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/services.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/quad.h
strchr.o: strchr.c /home/mycure/kaneton/libs/klibc/include/klibc.h \
  /home/mycure/kaneton/libs/klibc/include/libc/libc.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/machdep.h \
  /home/mycure/kaneton/core/include/arch/machdep/asm.h \
  /home/mycure/kaneton/core/include/arch/machdep/stdarg.h \
  /home/mycure/kaneton/core/include/arch/machdep/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/multiboot.h \
  /home/mycure/kaneton/core/include/arch/machdep/elf.h \
  /home/mycure/kaneton/core/include/arch/machdep/kaneton.h \
  /home/mycure/kaneton/core/include/arch/machdep/init.h \
  /home/mycure/kaneton/core/include/arch/machdep/cons.h \
  /home/mycure/kaneton/core/include/arch/machdep/pmode.h \
  /home/mycure/kaneton/core/include/arch/machdep/paging.h \
  /home/mycure/kaneton/core/include/arch/machdep/bootloader.h \
  /home/mycure/kaneton/libs/klibc/include/libc/ctype.h \
  /home/mycure/kaneton/libs/klibc/include/libc/printf.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/errno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/limits.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/services.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/quad.h
strcmp.o: strcmp.c /home/mycure/kaneton/libs/klibc/include/klibc.h \
  /home/mycure/kaneton/libs/klibc/include/libc/libc.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/machdep.h \
  /home/mycure/kaneton/core/include/arch/machdep/asm.h \
  /home/mycure/kaneton/core/include/arch/machdep/stdarg.h \
  /home/mycure/kaneton/core/include/arch/machdep/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/multiboot.h \
  /home/mycure/kaneton/core/include/arch/machdep/elf.h \
  /home/mycure/kaneton/core/include/arch/machdep/kaneton.h \
  /home/mycure/kaneton/core/include/arch/machdep/init.h \
  /home/mycure/kaneton/core/include/arch/machdep/cons.h \
  /home/mycure/kaneton/core/include/arch/machdep/pmode.h \
  /home/mycure/kaneton/core/include/arch/machdep/paging.h \
  /home/mycure/kaneton/core/include/arch/machdep/bootloader.h \
  /home/mycure/kaneton/libs/klibc/include/libc/ctype.h \
  /home/mycure/kaneton/libs/klibc/include/libc/printf.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/errno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/limits.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/services.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/quad.h
strcpy.o: strcpy.c /home/mycure/kaneton/libs/klibc/include/klibc.h \
  /home/mycure/kaneton/libs/klibc/include/libc/libc.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/machdep.h \
  /home/mycure/kaneton/core/include/arch/machdep/asm.h \
  /home/mycure/kaneton/core/include/arch/machdep/stdarg.h \
  /home/mycure/kaneton/core/include/arch/machdep/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/multiboot.h \
  /home/mycure/kaneton/core/include/arch/machdep/elf.h \
  /home/mycure/kaneton/core/include/arch/machdep/kaneton.h \
  /home/mycure/kaneton/core/include/arch/machdep/init.h \
  /home/mycure/kaneton/core/include/arch/machdep/cons.h \
  /home/mycure/kaneton/core/include/arch/machdep/pmode.h \
  /home/mycure/kaneton/core/include/arch/machdep/paging.h \
  /home/mycure/kaneton/core/include/arch/machdep/bootloader.h \
  /home/mycure/kaneton/libs/klibc/include/libc/ctype.h \
  /home/mycure/kaneton/libs/klibc/include/libc/printf.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/errno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/limits.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/services.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/quad.h
strlen.o: strlen.c /home/mycure/kaneton/libs/klibc/include/klibc.h \
  /home/mycure/kaneton/libs/klibc/include/libc/libc.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/machdep.h \
  /home/mycure/kaneton/core/include/arch/machdep/asm.h \
  /home/mycure/kaneton/core/include/arch/machdep/stdarg.h \
  /home/mycure/kaneton/core/include/arch/machdep/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/multiboot.h \
  /home/mycure/kaneton/core/include/arch/machdep/elf.h \
  /home/mycure/kaneton/core/include/arch/machdep/kaneton.h \
  /home/mycure/kaneton/core/include/arch/machdep/init.h \
  /home/mycure/kaneton/core/include/arch/machdep/cons.h \
  /home/mycure/kaneton/core/include/arch/machdep/pmode.h \
  /home/mycure/kaneton/core/include/arch/machdep/paging.h \
  /home/mycure/kaneton/core/include/arch/machdep/bootloader.h \
  /home/mycure/kaneton/libs/klibc/include/libc/ctype.h \
  /home/mycure/kaneton/libs/klibc/include/libc/printf.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/errno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/limits.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/services.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/quad.h
strncat.o: strncat.c /home/mycure/kaneton/libs/klibc/include/klibc.h \
  /home/mycure/kaneton/libs/klibc/include/libc/libc.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/machdep.h \
  /home/mycure/kaneton/core/include/arch/machdep/asm.h \
  /home/mycure/kaneton/core/include/arch/machdep/stdarg.h \
  /home/mycure/kaneton/core/include/arch/machdep/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/multiboot.h \
  /home/mycure/kaneton/core/include/arch/machdep/elf.h \
  /home/mycure/kaneton/core/include/arch/machdep/kaneton.h \
  /home/mycure/kaneton/core/include/arch/machdep/init.h \
  /home/mycure/kaneton/core/include/arch/machdep/cons.h \
  /home/mycure/kaneton/core/include/arch/machdep/pmode.h \
  /home/mycure/kaneton/core/include/arch/machdep/paging.h \
  /home/mycure/kaneton/core/include/arch/machdep/bootloader.h \
  /home/mycure/kaneton/libs/klibc/include/libc/ctype.h \
  /home/mycure/kaneton/libs/klibc/include/libc/printf.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/errno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/limits.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/services.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/quad.h
strncmp.o: strncmp.c /home/mycure/kaneton/libs/klibc/include/klibc.h \
  /home/mycure/kaneton/libs/klibc/include/libc/libc.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/machdep.h \
  /home/mycure/kaneton/core/include/arch/machdep/asm.h \
  /home/mycure/kaneton/core/include/arch/machdep/stdarg.h \
  /home/mycure/kaneton/core/include/arch/machdep/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/multiboot.h \
  /home/mycure/kaneton/core/include/arch/machdep/elf.h \
  /home/mycure/kaneton/core/include/arch/machdep/kaneton.h \
  /home/mycure/kaneton/core/include/arch/machdep/init.h \
  /home/mycure/kaneton/core/include/arch/machdep/cons.h \
  /home/mycure/kaneton/core/include/arch/machdep/pmode.h \
  /home/mycure/kaneton/core/include/arch/machdep/paging.h \
  /home/mycure/kaneton/core/include/arch/machdep/bootloader.h \
  /home/mycure/kaneton/libs/klibc/include/libc/ctype.h \
  /home/mycure/kaneton/libs/klibc/include/libc/printf.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/errno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/limits.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/services.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/quad.h
strncpy.o: strncpy.c /home/mycure/kaneton/libs/klibc/include/klibc.h \
  /home/mycure/kaneton/libs/klibc/include/libc/libc.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/machdep.h \
  /home/mycure/kaneton/core/include/arch/machdep/asm.h \
  /home/mycure/kaneton/core/include/arch/machdep/stdarg.h \
  /home/mycure/kaneton/core/include/arch/machdep/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/multiboot.h \
  /home/mycure/kaneton/core/include/arch/machdep/elf.h \
  /home/mycure/kaneton/core/include/arch/machdep/kaneton.h \
  /home/mycure/kaneton/core/include/arch/machdep/init.h \
  /home/mycure/kaneton/core/include/arch/machdep/cons.h \
  /home/mycure/kaneton/core/include/arch/machdep/pmode.h \
  /home/mycure/kaneton/core/include/arch/machdep/paging.h \
  /home/mycure/kaneton/core/include/arch/machdep/bootloader.h \
  /home/mycure/kaneton/libs/klibc/include/libc/ctype.h \
  /home/mycure/kaneton/libs/klibc/include/libc/printf.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/errno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/limits.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/services.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/quad.h
strtol.o: strtol.c /home/mycure/kaneton/libs/klibc/include/klibc.h \
  /home/mycure/kaneton/libs/klibc/include/libc/libc.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/machdep.h \
  /home/mycure/kaneton/core/include/arch/machdep/asm.h \
  /home/mycure/kaneton/core/include/arch/machdep/stdarg.h \
  /home/mycure/kaneton/core/include/arch/machdep/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/multiboot.h \
  /home/mycure/kaneton/core/include/arch/machdep/elf.h \
  /home/mycure/kaneton/core/include/arch/machdep/kaneton.h \
  /home/mycure/kaneton/core/include/arch/machdep/init.h \
  /home/mycure/kaneton/core/include/arch/machdep/cons.h \
  /home/mycure/kaneton/core/include/arch/machdep/pmode.h \
  /home/mycure/kaneton/core/include/arch/machdep/paging.h \
  /home/mycure/kaneton/core/include/arch/machdep/bootloader.h \
  /home/mycure/kaneton/libs/klibc/include/libc/ctype.h \
  /home/mycure/kaneton/libs/klibc/include/libc/printf.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/errno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/limits.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/services.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/quad.h
strtoul.o: strtoul.c /home/mycure/kaneton/libs/klibc/include/klibc.h \
  /home/mycure/kaneton/libs/klibc/include/libc/libc.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/machdep.h \
  /home/mycure/kaneton/core/include/arch/machdep/asm.h \
  /home/mycure/kaneton/core/include/arch/machdep/stdarg.h \
  /home/mycure/kaneton/core/include/arch/machdep/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/multiboot.h \
  /home/mycure/kaneton/core/include/arch/machdep/elf.h \
  /home/mycure/kaneton/core/include/arch/machdep/kaneton.h \
  /home/mycure/kaneton/core/include/arch/machdep/init.h \
  /home/mycure/kaneton/core/include/arch/machdep/cons.h \
  /home/mycure/kaneton/core/include/arch/machdep/pmode.h \
  /home/mycure/kaneton/core/include/arch/machdep/paging.h \
  /home/mycure/kaneton/core/include/arch/machdep/bootloader.h \
  /home/mycure/kaneton/libs/klibc/include/libc/ctype.h \
  /home/mycure/kaneton/libs/klibc/include/libc/printf.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/errno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/limits.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/services.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/quad.h
sum2.o: sum2.c /home/mycure/kaneton/libs/klibc/include/klibc.h \
  /home/mycure/kaneton/libs/klibc/include/libc/libc.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/machdep.h \
  /home/mycure/kaneton/core/include/arch/machdep/asm.h \
  /home/mycure/kaneton/core/include/arch/machdep/stdarg.h \
  /home/mycure/kaneton/core/include/arch/machdep/types.h \
  /home/mycure/kaneton/core/include/arch/machdep/multiboot.h \
  /home/mycure/kaneton/core/include/arch/machdep/elf.h \
  /home/mycure/kaneton/core/include/arch/machdep/kaneton.h \
  /home/mycure/kaneton/core/include/arch/machdep/init.h \
  /home/mycure/kaneton/core/include/arch/machdep/cons.h \
  /home/mycure/kaneton/core/include/arch/machdep/pmode.h \
  /home/mycure/kaneton/core/include/arch/machdep/paging.h \
  /home/mycure/kaneton/core/include/arch/machdep/bootloader.h \
  /home/mycure/kaneton/libs/klibc/include/libc/ctype.h \
  /home/mycure/kaneton/libs/klibc/include/libc/printf.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/libsys.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/errno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/limits.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/services.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/suberrno.h \
  /home/mycure/kaneton/libs/klibc/include/libsys/quad.h
