##
## kaneton
## 
## Makefile
## 
## path          /home/mycure/kaneton/source/papers
## 
## made by mycure
##         quintard julien   [quinta_j@epita.fr]
## 
## started on    Sun Nov 21 14:13:54 2004   mycure
## last update   Thu Jan 28 05:58:48 1999   mycure
##

#
# file
#

_FILE_			:=		design

#
# dependency
#

include			../makefile.mk
