#
# ---------- header -----------------------------------------------------------
#
# project       kaneton
#
# license       kaneton
#
# file          /home/mycure/kaneton/cheat/Makefile
#
# created       julien quintard   [sun jun 10 14:42:10 2007]
# updated       julien quintard   [sun jun 10 14:42:31 2007]
#

#
# ---------- dependencies -----------------------------------------------------
#

include			../environment/env.mk

#
# ---------- directives -------------------------------------------------------
#

.PHONY:		main clear prototypes headers dependencies

#
# ---------- rules ------------------------------------------------------------
#

main:

clear:
	$(call env_purge,)

prototypes:

headers:

dependencies:
