##
## licence       kaneton licence
##
## project       kaneton
##
## file          /home/mycure/kaneton/cheat/Makefile
##
## created       julien quintard   [sat jan 21 23:56:47 2006]
## updated       julien quintard   [mon feb 20 22:54:58 2006]
##

#
# ---------- dependencies -----------------------------------------------------
#

include			../environment/env.mk

#
# ---------- directives -------------------------------------------------------
#

.PHONY:		all clear proto dep

#
# ---------- rules ------------------------------------------------------------
#

all:

clear:
	$(call env_purge,)

proto:

dep:
