##
## kaneton
## 
## Makefile
## 
## path          /home/mycure/kaneton/source/papers/lectures/advanced-makefiles
## 
## made by mycure
##         quintard julien   [quinta_j@epita.fr]
## 
## started on    Sun Nov 21 14:13:54 2004   mycure
## last update   Thu Jan 28 06:04:36 1999   mycure
##

#
# file
#

_FILE_			:=		advanced-makefiles

#
# dependency
#

include			../../makefile.mk
