#
# ---------- header -----------------------------------------------------------
#
# project       kaneton
#
# license       kaneton
#
# file          /home/mycure/kaneton/configure/Makefile
#
# created       julien quintard   [wed may 16 18:08:19 2007]
# updated       julien quintard   [mon jun 11 19:28:57 2007]
#

#
# ---------- dependencies -----------------------------------------------------
#

include			../environment/env.mk

#
# ---------- directives -------------------------------------------------------
#

.PHONY:		main clear prototypes headers

#
# ---------- rules ------------------------------------------------------------
#

main:
	$(call env_launch,$(_CONFIGURE_SCRIPT_),,)

clear:
	$(call env_purge)

prototypes:

headers:
