##
## copyright quintard julien
## 
## kaneton
## 
## Makefile
## 
## path          /home/mycure/kaneton/core/bootstrap/arch
## 
## made by mycure
##         quintard julien   [quinta_j@epita.fr]
## 
## started on    Fri Feb 11 02:57:24 2005   mycure
## last update   Sat Jun  4 20:53:54 2005   mycure
##

include			../../../.common.mk

all:
	@cd machdep							; \
	make								; \
	cd ..

distclean:
	@cd machdep							; \
	make distclean							; \
	cd ..

proto:
	@cd machdep							; \
	make proto							; \
	cd ..
