##
## kaneton
## 
## Makefile
## 
## path          /home/mycure/kaneton/papers/lectures/distributed-operating-systems
## 
## made by mycure
##         quintard julien   [quinta_j@epita.fr]
## 
## started on    Sun Nov 21 14:13:54 2004   mycure
## last update   Fri Aug 19 21:47:13 2005   mycure
##

#
# file
#

_FILE_			:=		distributed-operating-systems

#
# dependency
#

include			../../makefile.mk
