##
## licence       kaneton licence
##
## project       kaneton
##
## file          /home/mycure/kaneton/view/template/Makefile
##
## created       julien quintard   [sat dec  3 22:53:10 2005]
## updated       julien quintard   [sat dec  3 22:55:36 2005]
##

#
# ---------- dependencies -----------------------------------------------------
#

include			../../env/.env.mk

#
# ---------- directives -------------------------------------------------------
#

.PHONY:		all clear proto dep

#
# ---------- rules ------------------------------------------------------------
#

all:

clear:
	$(call purge)

proto:

dep:
