##
## Makefile for epitar in /u/a1/ah-tec_m/ah-tec_m-tar
## 
## Made by mathieu ah-tec
## Login   <ah-tec_m@epita.fr>
## 
## Started on  Sat Jul  8 17:35:13 2006 mathieu ah-tec
## Last update Sat Jul  8 17:35:15 2006 mathieu ah-tec
##

all:
	cd src; gmake; cp epitar ../;

clean:
	cd src; gmake clean;

distclean: clean
	rm -f epitar