#! /bin/sh

for i in 1 2 3 4 5 6 7 8 9
do
	user="user-$i"
	ssh compile "yes | adduser --ingroup users --disabled-password $user" > /dev/null 2>&1
	[ "$?" -eq 0 ] && break
done
[ "$?" -ne 0 ] && echo "Cannot create the compile user." >&2  && exit 1

ssh compile "mkdir -m 700 ~$user/.ssh && 		\
             cp ~/.ssh/authorized_keys ~$user/.ssh &&	\
			 chown -R $user ~$user &&			\
			 chmod 700 ~$user"

rsync -avzr . $user@compile:kaneton

ssh $user@compile "export KANETON_PYTHON=/usr/bin/python	\
	            export KANETON_HOST=linux/ia32		\
		    export KANETON_USER=test			\
		    export KANETON_PLATFORM=ibm-pc		\
		    export KANETON_ARCHITECTURE=ia32		\
		    env &&					\
		    yes | make -C kaneton initialize &&		\
		    make -C kaneton clear &&			\
		    yes | make -C kaneton initialize &&		\
		    yes | make -C kaneton build &&		\
		    yes | make -C kaneton install" 2>&1

scp $user@compile:kaneton/kaneton.img . > /dev/null 2>&1

ssh compile "deluser --remove-home $user" 
