#! /bin/sh

name=`md5sum kaneton.img | cut -d' ' -f1`

[ ! -r xen.cfg ] && cat > xen.cfg <<EOF
kernel = "/usr/lib64/xen/boot/hvmloader"
builder='hvm'
memory = 128
name = "$name"
disk=['file:$TEST_DIR/root/kaneton.iso,hdc:cdrom,r']
boot="d"
vnc=1
serial='pty'
EOF

get_pts()
{
	cat "/var/log/xen/qemu-dm-$name.log" | sed -nre 's/char device redirected to (.*)/\1/p'
}

tmp_out=`mktemp`
enable_log=0

xm create xen.cfg > /dev/null
pts=`get_pts`

timeout 10 cat "$pts" 2>/dev/null | while read l
do
	l=`echo "$l" | sed -re 's///g'`

	case "$l" in
		*"wait for command ...")
			pts=`get_pts`
			echo "set noecho" > "$pts"
			echo "call $TEST_SYMBOL" > "$pts"
			;;
		"set noecho")
			enable_log=1
			;;
		*" called")
			xm destroy "$name"
			;;
		*)
			[ "$enable_log" -eq 1 ] && echo "$l" >> "$tmp_out"
			;;
	esac
done


xm list | grep "$name" > /dev/null && xm destroy "$name"

diff -u "check/$TEST_PATH/$TEST_NAME.res" "$tmp_out"
