##
## licence       kaneton licence
##
## project       kaneton
##
## file          /home/buckman/kaneton/env/Makefile
##
## created       julien quintard   [fri feb 11 02:59:20 2005]
## updated       matthieu bucchianeri   [tue jan 24 11:42:31 2006]
##

#
# ---------- dependencies -----------------------------------------------------
#

include			.env.mk

#
# ---------- directives -------------------------------------------------------
#

.PHONY:		all clear proto dep

#
# ---------- rules ------------------------------------------------------------
#

all:

clear:
	$(call purge,)

proto:

dep:
