#
# ---------- header -----------------------------------------------------------
#
# project       kaneton
#
# license       kaneton
#
# file          /home/mycure/kaneton/export/Makefile
#
# created       julien quintard   [sun jun 10 14:53:00 2007]
# updated       julien quintard   [mon jun 11 19:29:21 2007]
#

#
# ---------- dependencies -----------------------------------------------------
#

include			../../environment/env.mk

#
# ---------- directives -------------------------------------------------------
#

.PHONY:		main clear prototypes headers

#
# ---------- rules ------------------------------------------------------------
#

main:

clear:
	$(call env_purge)

prototypes:

headers:
