##
## kaneton
## 
## Makefile
## 
## path          /home/mycure/data/research/projects/kaneton/courses/advanced-makefiles
## 
## made by mycure
##         quintard julien   [quinta_j@epita.fr]
## 
## started on    Sun Nov 21 14:13:54 2004   mycure
## last update   Tue Jul  5 12:17:17 2005   mycure
##

#
# file
#

_FILE_			:=		advanced-makefiles

#
# dependency
#

include			../makefile.mk
