/*
 * project       kaneton
 *
 * generated by gen_interface.rb
 *
 */

/*
 * ---------- information -----------------------------------------------------
 *
 * this file implements user side of system calls.
 *
 */

/*
 * ---------- includes --------------------------------------------------------
 */

#include <libc.h>
#include <kaneton.h>

/*
 * ---------- functions -------------------------------------------------------
 */

t_error		syscall_as_give(i_task		arg1,
			t_id		arg2)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_AS_GIVE;
  message.u.request.u.as_give.arg1 = arg1;
  message.u.request.u.as_give.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_as_vaddr(t_id		arg1,
			t_paddr		arg2,
			t_vaddr*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_AS_VADDR;
  message.u.request.u.as_vaddr.arg1 = arg1;
  message.u.request.u.as_vaddr.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.as_vaddr.result1;

  return (ERROR_NONE);
}

t_error		syscall_as_paddr(t_id		arg1,
			t_vaddr		arg2,
			t_paddr*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_AS_PADDR;
  message.u.request.u.as_paddr.arg1 = arg1;
  message.u.request.u.as_paddr.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.as_paddr.result1;

  return (ERROR_NONE);
}

t_error		syscall_as_copy(t_id		arg1,
			t_vaddr		arg2,
			i_as		arg3,
			t_vaddr		arg4,
			t_vsize		arg5)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_AS_COPY;
  message.u.request.u.as_copy.arg1 = arg1;
  message.u.request.u.as_copy.arg2 = arg2;
  message.u.request.u.as_copy.arg3 = arg3;
  message.u.request.u.as_copy.arg4 = arg4;
  message.u.request.u.as_copy.arg5 = arg5;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_as_clone(i_task		arg1,
			t_id		arg2,
			i_as*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_AS_CLONE;
  message.u.request.u.as_clone.arg1 = arg1;
  message.u.request.u.as_clone.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.as_clone.result1;

  return (ERROR_NONE);
}

t_error		syscall_as_reserve(i_task		arg1,
			i_as*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_AS_RESERVE;
  message.u.request.u.as_reserve.arg1 = arg1;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.as_reserve.result1;

  return (ERROR_NONE);
}

t_error		syscall_as_release(t_id		arg1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_AS_RELEASE;
  message.u.request.u.as_release.arg1 = arg1;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_as_get(t_id		arg1,
			o_as*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_AS_GET;
  message.u.request.u.as_get.arg1 = arg1;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.as_get.result1;

  return (ERROR_NONE);
}

t_error		syscall_capability_reserve(t_id		arg1,
			t_operations		arg2,
			t_capability*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_CAPABILITY_RESERVE;
  message.u.request.u.capability_reserve.arg1 = arg1;
  message.u.request.u.capability_reserve.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.capability_reserve.result1;

  return (ERROR_NONE);
}

t_error		syscall_capability_release(t_id		arg1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_CAPABILITY_RELEASE;
  message.u.request.u.capability_release.arg1 = arg1;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_capability_restrict(t_id		arg1,
			t_operations		arg2,
			t_capability*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_CAPABILITY_RESTRICT;
  message.u.request.u.capability_restrict.arg1 = arg1;
  message.u.request.u.capability_restrict.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.capability_restrict.result1;

  return (ERROR_NONE);
}

t_error		syscall_capability_invalidate(t_id		arg1,
			t_id		arg2)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_CAPABILITY_INVALIDATE;
  message.u.request.u.capability_invalidate.arg1 = arg1;
  message.u.request.u.capability_invalidate.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_capability_get(t_id		arg1,
			t_capability_descriptor*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_CAPABILITY_GET;
  message.u.request.u.capability_get.arg1 = arg1;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.capability_get.result1;

  return (ERROR_NONE);
}

t_error		syscall_capability_give(t_id		arg1,
			i_node		arg2)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_CAPABILITY_GIVE;
  message.u.request.u.capability_give.arg1 = arg1;
  message.u.request.u.capability_give.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_capability_verify(t_capability*		arg1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_CAPABILITY_VERIFY;
  message.u.request.u.capability_verify.arg1 = *arg1;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_event_reserve(t_id		arg1,
			t_type		arg2,
			u_event_handler		arg3)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_EVENT_RESERVE;
  message.u.request.u.event_reserve.arg1 = arg1;
  message.u.request.u.event_reserve.arg2 = arg2;
  message.u.request.u.event_reserve.arg3 = arg3;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_event_release(t_id		arg1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_EVENT_RELEASE;
  message.u.request.u.event_release.arg1 = arg1;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_event_get(t_id		arg1,
			o_event*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_EVENT_GET;
  message.u.request.u.event_get.arg1 = arg1;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.event_get.result1;

  return (ERROR_NONE);
}

t_error		syscall_io_grant(t_id		arg1,
			i_task		arg2,
			t_uint8		arg3)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_IO_GRANT;
  message.u.request.u.io_grant.arg1 = arg1;
  message.u.request.u.io_grant.arg2 = arg2;
  message.u.request.u.io_grant.arg3 = arg3;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_io_deny(t_id		arg1,
			i_task		arg2,
			t_uint8		arg3)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_IO_DENY;
  message.u.request.u.io_deny.arg1 = arg1;
  message.u.request.u.io_deny.arg2 = arg2;
  message.u.request.u.io_deny.arg3 = arg3;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_io_read_8(i_task		arg1,
			t_id		arg2,
			t_uint8*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_IO_READ_8;
  message.u.request.u.io_read_8.arg1 = arg1;
  message.u.request.u.io_read_8.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.io_read_8.result1;

  return (ERROR_NONE);
}

t_error		syscall_io_read_16(i_task		arg1,
			t_id		arg2,
			t_uint16*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_IO_READ_16;
  message.u.request.u.io_read_16.arg1 = arg1;
  message.u.request.u.io_read_16.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.io_read_16.result1;

  return (ERROR_NONE);
}

t_error		syscall_io_read_32(i_task		arg1,
			t_id		arg2,
			t_uint32*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_IO_READ_32;
  message.u.request.u.io_read_32.arg1 = arg1;
  message.u.request.u.io_read_32.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.io_read_32.result1;

  return (ERROR_NONE);
}

t_error		syscall_io_read_64(i_task		arg1,
			t_id		arg2,
			t_uint64*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_IO_READ_64;
  message.u.request.u.io_read_64.arg1 = arg1;
  message.u.request.u.io_read_64.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.io_read_64.result1;

  return (ERROR_NONE);
}

t_error		syscall_io_write_8(i_task		arg1,
			t_id		arg2,
			t_uint8		arg3)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_IO_WRITE_8;
  message.u.request.u.io_write_8.arg1 = arg1;
  message.u.request.u.io_write_8.arg2 = arg2;
  message.u.request.u.io_write_8.arg3 = arg3;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_io_write_16(i_task		arg1,
			t_id		arg2,
			t_uint16		arg3)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_IO_WRITE_16;
  message.u.request.u.io_write_16.arg1 = arg1;
  message.u.request.u.io_write_16.arg2 = arg2;
  message.u.request.u.io_write_16.arg3 = arg3;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_io_write_32(i_task		arg1,
			t_id		arg2,
			t_uint32		arg3)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_IO_WRITE_32;
  message.u.request.u.io_write_32.arg1 = arg1;
  message.u.request.u.io_write_32.arg2 = arg2;
  message.u.request.u.io_write_32.arg3 = arg3;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_io_write_64(i_task		arg1,
			t_id		arg2,
			t_uint64		arg3)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_IO_WRITE_64;
  message.u.request.u.io_write_64.arg1 = arg1;
  message.u.request.u.io_write_64.arg2 = arg2;
  message.u.request.u.io_write_64.arg3 = arg3;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_map_reserve(t_id		arg1,
			t_opts		arg2,
			t_vsize		arg3,
			t_perms		arg4,
			t_vaddr*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_MAP_RESERVE;
  message.u.request.u.map_reserve.arg1 = arg1;
  message.u.request.u.map_reserve.arg2 = arg2;
  message.u.request.u.map_reserve.arg3 = arg3;
  message.u.request.u.map_reserve.arg4 = arg4;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.map_reserve.result1;

  return (ERROR_NONE);
}

t_error		syscall_map_release(t_id		arg1,
			t_vaddr		arg2)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_MAP_RELEASE;
  message.u.request.u.map_release.arg1 = arg1;
  message.u.request.u.map_release.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_map_resize(t_id		arg1,
			t_vaddr		arg2,
			t_vsize		arg3,
			t_vaddr*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_MAP_RESIZE;
  message.u.request.u.map_resize.arg1 = arg1;
  message.u.request.u.map_resize.arg2 = arg2;
  message.u.request.u.map_resize.arg3 = arg3;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.map_resize.result1;

  return (ERROR_NONE);
}

t_error		syscall_message_register(i_task		arg1,
			t_tag		arg2)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_MESSAGE_REGISTER;
  message.u.request.u.message_register.arg1 = arg1;
  message.u.request.u.message_register.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_region_reserve(t_id		arg1,
			i_segment		arg2,
			t_paddr		arg3,
			t_opts		arg4,
			t_vaddr		arg5,
			t_vsize		arg6,
			i_region*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_REGION_RESERVE;
  message.u.request.u.region_reserve.arg1 = arg1;
  message.u.request.u.region_reserve.arg2 = arg2;
  message.u.request.u.region_reserve.arg3 = arg3;
  message.u.request.u.region_reserve.arg4 = arg4;
  message.u.request.u.region_reserve.arg5 = arg5;
  message.u.request.u.region_reserve.arg6 = arg6;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.region_reserve.result1;

  return (ERROR_NONE);
}

t_error		syscall_region_release(i_as		arg1,
			t_id		arg2)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_REGION_RELEASE;
  message.u.request.u.region_release.arg1 = arg1;
  message.u.request.u.region_release.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_region_get(i_as		arg1,
			t_id		arg2,
			o_region*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_REGION_GET;
  message.u.request.u.region_get.arg1 = arg1;
  message.u.request.u.region_get.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.region_get.result1;

  return (ERROR_NONE);
}

t_error		syscall_sched_quantum(t_quantum		arg1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_SCHED_QUANTUM;
  message.u.request.u.sched_quantum.arg1 = arg1;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_sched_yield(i_cpu		arg1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_SCHED_YIELD;
  message.u.request.u.sched_yield.arg1 = arg1;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_sched_current(i_thread*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_SCHED_CURRENT;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.sched_current.result1;

  return (ERROR_NONE);
}

t_error		syscall_sched_add(i_thread		arg1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_SCHED_ADD;
  message.u.request.u.sched_add.arg1 = arg1;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_sched_remove(i_thread		arg1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_SCHED_REMOVE;
  message.u.request.u.sched_remove.arg1 = arg1;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_sched_update(i_thread		arg1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_SCHED_UPDATE;
  message.u.request.u.sched_update.arg1 = arg1;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_segment_clone(i_as		arg1,
			t_id		arg2,
			i_segment*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_SEGMENT_CLONE;
  message.u.request.u.segment_clone.arg1 = arg1;
  message.u.request.u.segment_clone.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.segment_clone.result1;

  return (ERROR_NONE);
}

t_error		syscall_segment_give(i_as		arg1,
			t_id		arg2)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_SEGMENT_GIVE;
  message.u.request.u.segment_give.arg1 = arg1;
  message.u.request.u.segment_give.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_segment_copy(t_id		arg1,
			t_paddr		arg2,
			i_segment		arg3,
			t_paddr		arg4,
			t_psize		arg5)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_SEGMENT_COPY;
  message.u.request.u.segment_copy.arg1 = arg1;
  message.u.request.u.segment_copy.arg2 = arg2;
  message.u.request.u.segment_copy.arg3 = arg3;
  message.u.request.u.segment_copy.arg4 = arg4;
  message.u.request.u.segment_copy.arg5 = arg5;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_segment_reserve(i_as		arg1,
			t_psize		arg2,
			t_perms		arg3,
			i_segment*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_SEGMENT_RESERVE;
  message.u.request.u.segment_reserve.arg1 = arg1;
  message.u.request.u.segment_reserve.arg2 = arg2;
  message.u.request.u.segment_reserve.arg3 = arg3;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.segment_reserve.result1;

  return (ERROR_NONE);
}

t_error		syscall_segment_release(i_segment		arg1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_SEGMENT_RELEASE;
  message.u.request.u.segment_release.arg1 = arg1;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_segment_catch(i_as		arg1,
			t_id		arg2)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_SEGMENT_CATCH;
  message.u.request.u.segment_catch.arg1 = arg1;
  message.u.request.u.segment_catch.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_segment_perms(t_id		arg1,
			t_perms		arg2)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_SEGMENT_PERMS;
  message.u.request.u.segment_perms.arg1 = arg1;
  message.u.request.u.segment_perms.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_segment_type(t_id		arg1,
			t_type		arg2)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_SEGMENT_TYPE;
  message.u.request.u.segment_type.arg1 = arg1;
  message.u.request.u.segment_type.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_segment_get(t_id		arg1,
			o_segment*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_SEGMENT_GET;
  message.u.request.u.segment_get.arg1 = arg1;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.segment_get.result1;

  return (ERROR_NONE);
}

t_error		syscall_task_current(i_task*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_TASK_CURRENT;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.task_current.result1;

  return (ERROR_NONE);
}

t_error		syscall_task_clone(t_id		arg1,
			i_task*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_TASK_CLONE;
  message.u.request.u.task_clone.arg1 = arg1;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.task_clone.result1;

  return (ERROR_NONE);
}

t_error		syscall_task_reserve(t_class		arg1,
			t_behav		arg2,
			t_prior		arg3,
			i_task*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_TASK_RESERVE;
  message.u.request.u.task_reserve.arg1 = arg1;
  message.u.request.u.task_reserve.arg2 = arg2;
  message.u.request.u.task_reserve.arg3 = arg3;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.task_reserve.result1;

  return (ERROR_NONE);
}

t_error		syscall_task_release(t_id		arg1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_TASK_RELEASE;
  message.u.request.u.task_release.arg1 = arg1;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_task_priority(t_id		arg1,
			t_prior		arg2)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_TASK_PRIORITY;
  message.u.request.u.task_priority.arg1 = arg1;
  message.u.request.u.task_priority.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_task_state(t_id		arg1,
			t_state		arg2)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_TASK_STATE;
  message.u.request.u.task_state.arg1 = arg1;
  message.u.request.u.task_state.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_task_wait(t_id		arg1,
			t_opts		arg2,
			t_wait*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_TASK_WAIT;
  message.u.request.u.task_wait.arg1 = arg1;
  message.u.request.u.task_wait.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.task_wait.result1;

  return (ERROR_NONE);
}

t_error		syscall_task_get(t_id		arg1,
			o_task*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_TASK_GET;
  message.u.request.u.task_get.arg1 = arg1;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.task_get.result1;

  return (ERROR_NONE);
}

t_error		syscall_thread_give(i_task		arg1,
			t_id		arg2)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_THREAD_GIVE;
  message.u.request.u.thread_give.arg1 = arg1;
  message.u.request.u.thread_give.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_thread_clone(i_task		arg1,
			t_id		arg2,
			i_thread*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_THREAD_CLONE;
  message.u.request.u.thread_clone.arg1 = arg1;
  message.u.request.u.thread_clone.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.thread_clone.result1;

  return (ERROR_NONE);
}

t_error		syscall_thread_reserve(i_task		arg1,
			t_prior		arg2,
			i_thread*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_THREAD_RESERVE;
  message.u.request.u.thread_reserve.arg1 = arg1;
  message.u.request.u.thread_reserve.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.thread_reserve.result1;

  return (ERROR_NONE);
}

t_error		syscall_thread_release(t_id		arg1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_THREAD_RELEASE;
  message.u.request.u.thread_release.arg1 = arg1;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_thread_priority(t_id		arg1,
			t_prior		arg2)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_THREAD_PRIORITY;
  message.u.request.u.thread_priority.arg1 = arg1;
  message.u.request.u.thread_priority.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_thread_state(t_id		arg1,
			t_state		arg2)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_THREAD_STATE;
  message.u.request.u.thread_state.arg1 = arg1;
  message.u.request.u.thread_state.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_thread_stack(t_id		arg1,
			t_stack		arg2)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_THREAD_STACK;
  message.u.request.u.thread_stack.arg1 = arg1;
  message.u.request.u.thread_stack.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_thread_load(t_id		arg1,
			t_thread_context		arg2)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_THREAD_LOAD;
  message.u.request.u.thread_load.arg1 = arg1;
  message.u.request.u.thread_load.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_thread_store(t_id		arg1,
			t_thread_context*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_THREAD_STORE;
  message.u.request.u.thread_store.arg1 = arg1;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.thread_store.result1;

  return (ERROR_NONE);
}

t_error		syscall_thread_get(t_id		arg1,
			o_thread*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_THREAD_GET;
  message.u.request.u.thread_get.arg1 = arg1;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.thread_get.result1;

  return (ERROR_NONE);
}

t_error		syscall_timer_reserve(t_type		arg1,
			u_timer_handler		arg2,
			t_uint32		arg3,
			t_uint32		arg4,
			i_timer*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_TIMER_RESERVE;
  message.u.request.u.timer_reserve.arg1 = arg1;
  message.u.request.u.timer_reserve.arg2 = arg2;
  message.u.request.u.timer_reserve.arg3 = arg3;
  message.u.request.u.timer_reserve.arg4 = arg4;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.timer_reserve.result1;

  return (ERROR_NONE);
}

t_error		syscall_timer_release(t_id		arg1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_TIMER_RELEASE;
  message.u.request.u.timer_release.arg1 = arg1;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_timer_delay(t_id		arg1,
			t_uint32		arg2)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_TIMER_DELAY;
  message.u.request.u.timer_delay.arg1 = arg1;
  message.u.request.u.timer_delay.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_timer_repeat(t_id		arg1,
			t_uint32		arg2)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_TIMER_REPEAT;
  message.u.request.u.timer_repeat.arg1 = arg1;
  message.u.request.u.timer_repeat.arg2 = arg2;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_timer_modify(t_id		arg1,
			t_uint32		arg2,
			t_uint32		arg3)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_TIMER_MODIFY;
  message.u.request.u.timer_modify.arg1 = arg1;
  message.u.request.u.timer_modify.arg2 = arg2;
  message.u.request.u.timer_modify.arg3 = arg3;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);


  return (ERROR_NONE);
}

t_error		syscall_timer_get(t_id		arg1,
			o_timer*		result1)
{
  o_syscall		message;
  i_node		dest;

  dest.machine = 2^64;
  dest.task = 0;

  message.id = 0;
  message.node.machine = dest.machine;
  message.node.task = 1;

  message.u.request.operation = INTERFACE_TIMER_GET;
  message.u.request.u.timer_get.arg1 = arg1;

  syscall_async_send((t_uint32*)&dest, 0, &message, sizeof (message));

  while (syscall_async_recv(0, &message, sizeof (message)) != ERROR_NONE)
    ;

  if (message.u.reply.error != ERROR_NONE)
    return (ERROR_UNKNOWN);

  *result1 = message.u.reply.u.timer_get.result1;

  return (ERROR_NONE);
}


