##
## kaneton
## 
## Makefile
## 
## path          /home/mycure/kaneton/papers/lectures/inline-assembly
## 
## made by mycure
##         quintard julien   [quinta_j@epita.fr]
## 
## started on    Sun Nov 21 14:13:54 2004   mycure
## last update   Tue Sep  6 16:08:29 2005   mycure
##

#
# file
#

_FILE_			:=		inline-assembly

#
# dependency
#

include			../../makefile.mk
