#!/bin/sh
## copyright quintard julien
## 
## kaneton
## 
## init
## 
## path          /home/mycure/kaneton
## 
## made by mycure
##         quintard julien   [quinta_j@epita.fr]
## 
## started on    Fri Feb 11 02:58:21 2005   mycure
## last update   Sun Jun 12 21:08:26 2005   mycure
##

# INFORMATIONS
#
# this script has to be run in the directory src/
#
# this script must always be run by the script src/env/init



# CONFIGURATION FILE PATH
#
# the configuration file
CONF="conf/"$USER"/"$USER".conf"



# CONFIGURATION FILE VARIABLES
#
# default globals
ENVIRONMENT="unknown"
ARCHITECTURE="unknwon"



# INSTALL SPECIFIC VARIABLES
#
# generic names for this script
COMMON_MK=".common.mk"
KANETON_MK=".kaneton.mk"



# READ CONFIGURATION FILE
#
# function used to read the configuration file and to load
# important variables
read_kaneton_conf()
{
  # env
  ENVIRONMENT=`cat $CONF | grep -E "^ENVIRONMENT = .*$" | cut -b 15-`

  # architecture
  ARCHITECTURE=`cat $CONF | grep -E "^ARCHITECTURE = .*$" | cut -b 16-`
}



# INIT
#
# installs the environment for linux operating system
init()
{
  # makefile dependencies
  GENERIC_COMMON_MK="env/common.mk"
  GENERIC_KANETON_MK="env/"$ENVIRONMENT"/kaneton.mk"

  # links
  print "   installing machine-specific files" "+"
  ln -s -f $GENERIC_KANETON_MK $KANETON_MK

  # sed
  print "   generating makefile dependencies" "+"
  sed s/___kaneton_sed___/$(pwd | sed 's/\//\\\//g')/g $GENERIC_COMMON_MK \
      > $COMMON_MK

  # create the symbolic link for architecture dependencies
  print "   installing links to machine-dependent directories" "+"
  ln -s -f $ARCHITECTURE core/bootstrap/arch/machdep
  ln -s -f $ARCHITECTURE core/bootloader/arch/machdep
  ln -s -f $ARCHITECTURE core/include/arch/machdep
  ln -s -f $ARCHITECTURE core/kaneton/arch/machdep

  ln -s -f $ARCHITECTURE lds/arch/machdep
}



# PRINT A MESSAGE
#
# print a message with a header
print()
{
  msg=$1
  header=$2

  case "$header" in
    "+")
      echo -n -e '\E[;34m'"\033[1m[\033[0m"
      echo -n -e '\E[;32m'"\033[1m+\033[0m"
      echo -n -e '\E[;34m'"\033[1m]\033[0m"
      ;;

    "!")
      echo -n -e '\E[;34m'"\033[1m[\033[0m"
      echo -n -e '\E[;31m'"\033[1m!\033[0m"
      echo -n -e '\E[;34m'"\033[1m]\033[0m"
      ;;

    "?")
      echo -n -e '\E[;34m'"\033[1m[\033[0m"
      echo -n -e '\E[;33m'"\033[1m\033[5m?\033[0m\033[0m"
      echo -n -e '\E[;34m'"\033[1m]\033[0m"
      ;;

    *)
      ;;
  esac

  echo -e "\033[1m$msg\033[0m"
  tput sgr0
}



# ENTRY POINT
#
# entry point of this script

# call the read_kaneton_conf function
read_kaneton_conf

# install environment
init
