#!/bin/sh
## copyright quintard julien
## 
## kaneton
## 
## init
## 
## path          /home/mycure/kaneton
## 
## made by mycure
##         quintard julien   [quinta_j@epita.fr]
## 
## started on    Fri Feb 11 02:58:21 2005   mycure
## last update   Fri Jul  1 13:14:48 2005   mycure
##

# INFORMATIONS
#
# this script has to be run in the directory src/
#
# this script must always be run by the script src/env/init



# CONFIGURATION FILE PATH
#
# the configuration file
CONF="conf/"$USER"/"$USER".conf"



# CONFIGURATION FILE VARIABLES
#
# default globals
ENVIRONMENT="unknown"
ARCHITECTURE="unknwon"



# INSTALL SPECIFIC VARIABLES
#
# generic names for this script
KANETON_MK=".kaneton.mk"



# BINARIES
#
# the list of binaries used to compile the kaneton kernel on
# linux operating systems.
BINARIES="gcc make rm ar ranlib ld nasm ln"



# READ CONFIGURATION FILE
#
# function used to read the configuration file and to load
# important variables
read_kaneton_conf()
{
  # environment
  ENVIRONMENT=`cat $CONF | grep -E "^_ENVIRONMENT_ = .*$" | cut -b 17-`

  # architecture
  ARCHITECTURE=`cat $CONF | grep -E "^_ARCHITECTURE_ = .*$" | cut -b 18-`
}



# CHECK
#
# checks wheter the binaries used to compile the kaneton kernel are
# present on the system.
check()
{
  print "   checking binaries" "+"

  for i in $BINARIES ; do
    which $i 2> /dev/null > /dev/null
    if [ $? -ne 0 ] ; then
      print "    binary '$i' not present on your system" "!"
    fi
  done
}



# INIT
#
# installs the environment for linux operating system
init()
{
  # makefile dependencies
  GENERIC_KANETON_MK="env/"$ENVIRONMENT"/kaneton.mk"

  # sed
  print "   generating makefile dependencies" "+"

  rm -f $KANETON_MK

  sed s/___kaneton_sed___/$(pwd | sed 's/\//\\\//g')/g $GENERIC_KANETON_MK \
      > $KANETON_MK

  # create the symbolic link for architecture dependencies
  print "   installing links to machine-dependent directories" "+"

  rm -f core/bootstrap/arch/machdep
  rm -f core/bootloader/arch/machdep
  rm -f core/include/arch/machdep
  rm -f core/kaneton/arch/machdep
  rm -f lds/arch/machdep

  ln -s $ARCHITECTURE core/bootstrap/arch/machdep
  ln -s $ARCHITECTURE core/bootloader/arch/machdep
  ln -s $ARCHITECTURE core/include/arch/machdep
  ln -s $ARCHITECTURE core/kaneton/arch/machdep
  ln -s $ARCHITECTURE lds/arch/machdep
}



# PRINT A MESSAGE
#
# print a message with a header
print()
{
  msg=$1
  header=$2

  case "$header" in
    "+")
      echo -n -e '\E[;34m'"\033[1m[\033[0m"
      echo -n -e '\E[;32m'"\033[1m+\033[0m"
      echo -n -e '\E[;34m'"\033[1m]\033[0m"
      ;;

    "!")
      echo -n -e '\E[;34m'"\033[1m[\033[0m"
      echo -n -e '\E[;31m'"\033[1m!\033[0m"
      echo -n -e '\E[;34m'"\033[1m]\033[0m"
      ;;

    "?")
      echo -n -e '\E[;34m'"\033[1m[\033[0m"
      echo -n -e '\E[;33m'"\033[1m\033[5m?\033[0m\033[0m"
      echo -n -e '\E[;34m'"\033[1m]\033[0m"
      ;;

    *)
      ;;
  esac

  echo -e "\033[1m$msg\033[0m"
  tput sgr0
}



# ENTRY POINT
#
# entry point of this script

# call the read_kaneton_conf function
read_kaneton_conf

# install environment
init

# check the binaries
check
